// Maps Base44 CamelCase entity names to Supabase snake_case table names.
// Mirrors railway/src/lib/supabase.js tableName() — keep both in sync.

const TABLE_MAP = {
  BusinessAudit: 'business_audits',
  AuditFinding: 'audit_findings',
  Evidence: 'evidence',
  RevenueLeak: 'revenue_leaks',
  ScanSnapshot: 'scan_snapshots',
  AuditReceipt: 'audit_receipts',
  SystemNode: 'system_nodes',
  SystemEdge: 'system_edges',
  RepairPlan: 'repair_plans',
  RepairActionItem: 'repair_action_items',
  RiskRegister: 'risk_register',
  OutreachDraft: 'outreach_drafts',
  MonitoringRule: 'monitoring_rules',
  MonitoringEvent: 'monitoring_events',
  CloneQueue: 'clone_queue',
  FactoryProject: 'factory_projects',
  GeneratorRun: 'generator_runs',
  RunStep: 'run_steps',
  FactoryArtifact: 'factory_artifacts',
  ValidationReceipt: 'validation_receipts',
  RepairTask: 'repair_tasks',
  FactoryApproval: 'factory_approvals',
  ProvisioningPlan: 'provisioning_plans',
  ProvisionedSite: 'provisioned_sites',
  TemplateAsset: 'template_assets',
  TemplatePack: 'template_packs',
  GeneratorDefinition: 'generator_definitions',
  AdapterDefinition: 'adapter_definitions',
  Sandbox: 'sandboxes',
  AgentTask: 'agent_tasks',
  CatalogItem: 'catalog_items',
  CatalogQuote: 'catalog_quotes',
  CommerceOrder: 'commerce_orders',
  ClientInfrastructure: 'client_infrastructure',
  CustomerSite: 'customer_sites',
  ClientProject: 'client_projects',
  ProjectRequest: 'project_requests',
  Lead: 'leads',
  CrmContact: 'crm_contacts',
  Post: 'posts',
  post: 'posts',
  Project: 'projects',
  project: 'projects',
  Testimonial: 'testimonials',
  testimonial: 'testimonials',
  VaultAccount: 'vault_accounts',
  VaultAccessKey: 'vault_access_keys',
  AdminConversation: 'admin_conversations',
  AdminChatTurn: 'admin_chat_turns',
  BenchmarkRun: 'benchmark_runs',
  BenchmarkCheckpoint: 'benchmark_checkpoints',
  BenchmarkCompany: 'benchmark_companies',
  Domain: 'domains',
  DomainInventory: 'domain_inventory',
  DomainMetric: 'domain_metrics',
  DominanceGoal: 'dominance_goals',
  DominanceCampaign: 'dominance_campaigns',
  InsiderContent: 'insider_content',
  EnhancementJob: 'enhancement_jobs',
  SystemBuild: 'system_builds',
  WorkerFleet: 'worker_fleets',
  BatchOperation: 'batch_operations',
  Campaign: 'campaigns',
  CampaignRecipient: 'campaign_recipients',
  SmsConversation: 'sms_conversations',
  SmsMessage: 'sms_messages',
  CallLog: 'call_logs',
  CommsEvent: 'comms_events',
  Conversation: 'conversations',
  CommunicationTemplate: 'communication_templates',
  AgentPersona: 'agent_personas',
};

export function tableName(entityName) {
  return TABLE_MAP[entityName] ||
    entityName.replace(/([A-Z])/g, '_$1').toLowerCase().replace(/^_/, '');
}