// Universal Business Category Registry
// Pre-configured SEO data for the top business categories nationwide.
// Each category includes seed keywords, core services, default branding,
// and Google-standard SEO settings — so the mass launch system can
// generate hundreds of websites across any vertical.

export const UNIVERSAL_CATEGORIES = [
  {
    id: 'hvac',
    label: 'HVAC / Air Conditioning',
    keyword: 'hvac contractor',
    services: ['AC Repair', 'Heating Installation', 'Air Duct Cleaning', 'Furnace Service', 'Heat Pump Installation', 'Indoor Air Quality', 'Smart Thermostat Setup', 'Commercial HVAC'],
    defaultColors: { bg: '#0A1A3F', accent: '#0066FF' },
    seasonality: 'summer_winter',
    averageTicket: 4500,
  },
  {
    id: 'plumbing',
    label: 'Plumbing',
    keyword: 'plumber',
    services: ['Drain Cleaning', 'Water Heater Repair', 'Leak Detection', 'Sewer Line Service', 'Garbage Disposal Repair', 'Toilet Repair', 'Pipe Replacement', 'Emergency Plumbing'],
    defaultColors: { bg: '#0A1628', accent: '#0088CC' },
    seasonality: 'year_round',
    averageTicket: 800,
  },
  {
    id: 'roofing',
    label: 'Roofing',
    keyword: 'roofing contractor',
    services: ['Roof Replacement', 'Roof Repair', 'Storm Damage Restoration', 'Gutter Installation', 'Roof Inspection', 'Shingle Repair', 'Flat Roof Service', 'Skylight Installation'],
    defaultColors: { bg: '#1A1A1A', accent: '#CC4444' },
    seasonality: 'spring_summer',
    averageTicket: 12000,
  },
  {
    id: 'electrical',
    label: 'Electrical',
    keyword: 'electrician',
    services: ['Panel Upgrade', 'Wiring Repair', 'Lighting Installation', 'EV Charger Installation', 'Generator Setup', 'Outlet Repair', 'Safety Inspection', 'Commercial Electrical'],
    defaultColors: { bg: '#0D0D1A', accent: '#FFB800' },
    seasonality: 'year_round',
    averageTicket: 1200,
  },
  {
    id: 'epoxy_flooring',
    label: 'Epoxy / Concrete Flooring',
    keyword: 'epoxy flooring',
    services: ['Epoxy Garage Floors', 'Polished Concrete', 'Commercial Epoxy', 'Concrete Sealing', 'Metallic Epoxy', 'Flake Flooring', 'Concrete Resurfacing', 'Industrial Flooring'],
    defaultColors: { bg: '#1A1A2E', accent: '#D4A92E' },
    seasonality: 'year_round',
    averageTicket: 3500,
  },
  {
    id: 'landscaping',
    label: 'Landscaping',
    keyword: 'landscaping company',
    services: ['Lawn Care', 'Garden Design', 'Tree Service', 'Hardscaping', 'Irrigation Installation', 'Sod Installation', 'Landscape Lighting', 'Drainage Solutions'],
    defaultColors: { bg: '#0A2818', accent: '#2D8659' },
    seasonality: 'spring_summer_fall',
    averageTicket: 2500,
  },
  {
    id: 'pest_control',
    label: 'Pest Control',
    keyword: 'pest control service',
    services: ['Termite Treatment', 'Rodent Control', 'Bed Bug Extermination', 'Mosquito Control', 'Ant Control', 'Spider Control', 'Quarterly Pest Prevention', 'Commercial Pest Control'],
    defaultColors: { bg: '#1A0A0A', accent: '#CC3333' },
    seasonality: 'year_round',
    averageTicket: 350,
  },
  {
    id: 'dentist',
    label: 'Dental / Cosmetic Dentistry',
    keyword: 'dentist',
    services: ['Teeth Cleaning', 'Dental Implants', 'Teeth Whitening', 'Invisalign', 'Emergency Dental', 'Root Canal', 'Crowns & Bridges', 'Cosmetic Dentistry'],
    defaultColors: { bg: '#0A1A2E', accent: '#00AACC' },
    seasonality: 'year_round',
    averageTicket: 1800,
  },
  {
    id: 'law_firm',
    label: 'Law Firm / Legal',
    keyword: 'law firm',
    services: ['Personal Injury', 'Family Law', 'Criminal Defense', 'Estate Planning', 'Business Law', 'Bankruptcy', 'Immigration Law', 'Real Estate Law'],
    defaultColors: { bg: '#0A0A1A', accent: '#B8901E' },
    seasonality: 'year_round',
    averageTicket: 5000,
  },
  {
    id: 'med_spa',
    label: 'Med Spa / Aesthetics',
    keyword: 'med spa',
    services: ['Botox', 'Dermal Fillers', 'Laser Hair Removal', 'Chemical Peels', 'Microneedling', 'CoolSculpting', 'IV Therapy', 'Facial Treatments'],
    defaultColors: { bg: '#1A0A1A', accent: '#CC6699' },
    seasonality: 'year_round',
    averageTicket: 600,
  },
  {
    id: 'chiropractor',
    label: 'Chiropractor',
    keyword: 'chiropractor',
    services: ['Spinal Adjustment', 'Physical Therapy', 'Massage Therapy', 'Sports Injury Treatment', 'Auto Accident Recovery', 'Posture Correction', 'Wellness Care', 'Pediatric Chiropractic'],
    defaultColors: { bg: '#0A1A1A', accent: '#00AA88' },
    seasonality: 'year_round',
    averageTicket: 250,
  },
  {
    id: 'auto_repair',
    label: 'Auto Repair',
    keyword: 'auto repair shop',
    services: ['Oil Change', 'Brake Service', 'Transmission Repair', 'Engine Diagnostics', 'Tire Service', 'AC Repair', 'Battery Replacement', 'General Maintenance'],
    defaultColors: { bg: '#1A1A0A', accent: '#FF8800' },
    seasonality: 'year_round',
    averageTicket: 500,
  },
  {
    id: 'solar',
    label: 'Solar Installation',
    keyword: 'solar company',
    services: ['Solar Panel Installation', 'Solar Battery Storage', 'Solar System Design', 'Solar Repair & Maintenance', 'Commercial Solar', 'Solar Financing', 'Net Metering Setup', 'Solar Inspection'],
    defaultColors: { bg: '#0A1A2E', accent: '#FFB800' },
    seasonality: 'year_round',
    averageTicket: 25000,
  },
  {
    id: 'fence',
    label: 'Fence Installation',
    keyword: 'fence company',
    services: ['Wood Fence', 'Vinyl Fence', 'Chain Link Fence', 'Aluminum Fence', 'Gate Installation', 'Fence Repair', 'Privacy Fence', 'Commercial Fencing'],
    defaultColors: { bg: '#1A140A', accent: '#8B6914' },
    seasonality: 'spring_summer_fall',
    averageTicket: 3500,
  },
  {
    id: 'painting',
    label: 'Painting',
    keyword: 'painting contractor',
    services: ['Interior Painting', 'Exterior Painting', 'Commercial Painting', 'Cabinet Refinishing', 'Drywall Repair', 'Deck Staining', 'Wallpaper Removal', 'Power Washing'],
    defaultColors: { bg: '#0A0A1A', accent: '#0066FF' },
    seasonality: 'spring_summer_fall',
    averageTicket: 3000,
  },
  {
    id: 'cleaning',
    label: 'Cleaning Services',
    keyword: 'cleaning service',
    services: ['House Cleaning', 'Deep Cleaning', 'Move In/Out Cleaning', 'Commercial Cleaning', 'Carpet Cleaning', 'Window Cleaning', 'Post-Construction Cleaning', 'Recurring Cleaning'],
    defaultColors: { bg: '#0A1A2E', accent: '#00BBCC' },
    seasonality: 'year_round',
    averageTicket: 200,
  },
  {
    id: 'garage_door',
    label: 'Garage Door',
    keyword: 'garage door repair',
    services: ['Garage Door Repair', 'Garage Door Installation', 'Spring Replacement', 'Opener Repair', 'Panel Replacement', 'Track Repair', 'Smart Opener Setup', 'Commercial Garage Doors'],
    defaultColors: { bg: '#1A1A1A', accent: '#0066FF' },
    seasonality: 'year_round',
    averageTicket: 450,
  },
  {
    id: 'tree_service',
    label: 'Tree Service',
    keyword: 'tree service company',
    services: ['Tree Removal', 'Tree Trimming', 'Stump Grinding', 'Tree Health Assessment', 'Emergency Tree Service', 'Lot Clearing', 'Tree Pruning', 'Arborist Consultation'],
    defaultColors: { bg: '#0A1A0A', accent: '#2D8659' },
    seasonality: 'year_round',
    averageTicket: 1500,
  },
  {
    id: 'junk_removal',
    label: 'Junk Removal',
    keyword: 'junk removal service',
    services: ['Residential Junk Removal', 'Commercial Junk Removal', 'Furniture Removal', 'Appliance Disposal', 'Construction Debris', 'Estate Cleanout', 'Hoarding Cleanup', 'Yard Waste Removal'],
    defaultColors: { bg: '#1A0A0A', accent: '#CC6633' },
    seasonality: 'year_round',
    averageTicket: 400,
  },
  {
    id: 'moving',
    label: 'Moving Company',
    keyword: 'moving company',
    services: ['Local Moving', 'Long Distance Moving', 'Residential Moving', 'Commercial Moving', 'Packing Services', 'Storage Solutions', 'Furniture Moving', 'Senior Moving Services'],
    defaultColors: { bg: '#0A0A1A', accent: '#0066CC' },
    seasonality: 'summer_peak',
    averageTicket: 2000,
  },
  {
    id: 'pool',
    label: 'Pool Service',
    keyword: 'pool service company',
    services: ['Pool Cleaning', 'Pool Repair', 'Pool Maintenance', 'Pool Installation', 'Pool Resurfacing', 'Pool Tile Repair', 'Chemical Balancing', 'Spa Service'],
    defaultColors: { bg: '#0A1A2E', accent: '#00AAFF' },
    seasonality: 'summer_peak',
    averageTicket: 300,
  },
  {
    id: 'accounting',
    label: 'Accounting / CPA',
    keyword: 'accounting firm',
    services: ['Tax Preparation', 'Bookkeeping', 'Payroll Services', 'Business Consulting', 'IRS Representation', 'Financial Planning', 'Audit Services', 'Estate Tax Planning'],
    defaultColors: { bg: '#0A0A1A', accent: '#0066CC' },
    seasonality: 'tax_season',
    averageTicket: 1500,
  },
  {
    id: 'real_estate',
    label: 'Real Estate',
    keyword: 'real estate agent',
    services: ['Home Buying', 'Home Selling', 'Property Listings', 'Market Analysis', 'First Time Buyer', 'Luxury Homes', 'Commercial Real Estate', 'Property Management'],
    defaultColors: { bg: '#1A0A0A', accent: '#CC3333' },
    seasonality: 'spring_summer',
    averageTicket: 10000,
  },
  {
    id: 'insurance',
    label: 'Insurance Agency',
    keyword: 'insurance agency',
    services: ['Auto Insurance', 'Home Insurance', 'Life Insurance', 'Business Insurance', 'Health Insurance', 'Commercial Insurance', 'Flood Insurance', 'Umbrella Policies'],
    defaultColors: { bg: '#0A0A1A', accent: '#0066CC' },
    seasonality: 'year_round',
    averageTicket: 1200,
  },
  {
    id: 'veterinary',
    label: 'Veterinary',
    keyword: 'veterinary clinic',
    services: ['Wellness Exams', 'Vaccinations', 'Surgery', 'Dental Care', 'Emergency Care', 'Spay & Neuter', 'Microchipping', 'Senior Pet Care'],
    defaultColors: { bg: '#0A1A1A', accent: '#00AA88' },
    seasonality: 'year_round',
    averageTicket: 300,
  },
  {
    id: 'physical_therapy',
    label: 'Physical Therapy',
    keyword: 'physical therapy clinic',
    services: ['Sports Rehabilitation', 'Post-Surgery Recovery', 'Manual Therapy', 'Dry Needling', 'Balance Training', 'Work Injury Recovery', 'Pediatric PT', 'Wellness Programs'],
    defaultColors: { bg: '#0A1A1A', accent: '#00BBAA' },
    seasonality: 'year_round',
    averageTicket: 200,
  },
  {
    id: 'locksmith',
    label: 'Locksmith',
    keyword: 'locksmith service',
    services: ['Lockout Service', 'Lock Installation', 'Rekeying', 'Smart Lock Installation', 'Safe Opening', 'Car Key Replacement', 'Master Key Systems', 'Commercial Locksmith'],
    defaultColors: { bg: '#1A1A0A', accent: '#FFB800' },
    seasonality: 'year_round',
    averageTicket: 200,
  },
  {
    id: 'septic',
    label: 'Septic Service',
    keyword: 'septic tank service',
    services: ['Septic Pumping', 'Septic Installation', 'Septic Repair', 'Septic Inspection', 'Drain Field Repair', 'Septic Maintenance', 'Emergency Septic', 'Commercial Septic'],
    defaultColors: { bg: '#1A140A', accent: '#8B6914' },
    seasonality: 'year_round',
    averageTicket: 600,
  },
  {
    id: 'water_damage',
    label: 'Water Damage / Restoration',
    keyword: 'water damage restoration',
    services: ['Water Extraction', 'Flood Cleanup', 'Mold Remediation', 'Drying & Dehumidification', 'Storm Damage', 'Sewage Cleanup', 'Document Drying', 'Reconstruction'],
    defaultColors: { bg: '#0A1A2E', accent: '#0066FF' },
    seasonality: 'year_round',
    averageTicket: 5000,
  },
  {
    id: 'window',
    label: 'Window / Door Replacement',
    keyword: 'window replacement company',
    services: ['Window Installation', 'Window Replacement', 'Door Installation', 'Energy Efficient Windows', 'Bay & Bow Windows', 'Sliding Doors', 'Custom Windows', 'Window Repair'],
    defaultColors: { bg: '#0A0A1A', accent: '#0066CC' },
    seasonality: 'spring_summer_fall',
    averageTicket: 8000,
  },
];

export function getCategoryById(id) {
  return UNIVERSAL_CATEGORIES.find(c => c.id === id);
}

export function generateBusinessName(category, city) {
  const cat = getCategoryById(category);
  if (!cat) return `${city} Pro Services`;
  const prefixes = ['Premier', 'Elite', 'Pro', 'Apex', 'Summit', 'Pinnacle', 'Trusted', 'Reliable', 'Expert', 'Master'];
  const suffixes = ['Pros', 'Experts', 'Services', 'Solutions', 'Co', 'Group', 'Specialists', 'Masters'];
  const prefix = prefixes[Math.floor(Math.random() * prefixes.length)];
  const suffix = suffixes[Math.floor(Math.random() * suffixes.length)];
  return `${city} ${cat.label.split(' ')[0]} ${suffix}`;
}