// Top US cities for mass website launch — sorted by population.
// Used by the Mass Launch Console city picker for batch selection.

export const US_CITIES = [
  { city: 'New York', state: 'NY', population: 8336817 },
  { city: 'Los Angeles', state: 'CA', population: 3898747 },
  { city: 'Chicago', state: 'IL', population: 2693976 },
  { city: 'Houston', state: 'TX', population: 2304580 },
  { city: 'Phoenix', state: 'AZ', population: 1608139 },
  { city: 'Philadelphia', state: 'PA', population: 1603797 },
  { city: 'San Antonio', state: 'TX', population: 1434620 },
  { city: 'San Diego', state: 'CA', population: 1386932 },
  { city: 'Dallas', state: 'TX', population: 1304379 },
  { city: 'San Jose', state: 'CA', population: 1021795 },
  { city: 'Austin', state: 'TX', population: 978908 },
  { city: 'Jacksonville', state: 'FL', population: 911507 },
  { city: 'Fort Worth', state: 'TX', population: 909585 },
  { city: 'Columbus', state: 'OH', population: 898553 },
  { city: 'Indianapolis', state: 'IN', population: 876384 },
  { city: 'Charlotte', state: 'NC', population: 879093 },
  { city: 'San Francisco', state: 'CA', population: 873965 },
  { city: 'Seattle', state: 'WA', population: 753675 },
  { city: 'Denver', state: 'CO', population: 727211 },
  { city: 'Washington', state: 'DC', population: 689545 },
  { city: 'Boston', state: 'MA', population: 692600 },
  { city: 'El Paso', state: 'TX', population: 678815 },
  { city: 'Nashville', state: 'TN', population: 689447 },
  { city: 'Detroit', state: 'MI', population: 670031 },
  { city: 'Oklahoma City', state: 'OK', population: 655057 },
  { city: 'Portland', state: 'OR', population: 654741 },
  { city: 'Las Vegas', state: 'NV', population: 651319 },
  { city: 'Memphis', state: 'TN', population: 651073 },
  { city: 'Louisville', state: 'KY', population: 617638 },
  { city: 'Baltimore', state: 'MD', population: 593490 },
  { city: 'Milwaukee', state: 'WI', population: 590157 },
  { city: 'Albuquerque', state: 'NM', population: 560513 },
  { city: 'Tucson', state: 'AZ', population: 542629 },
  { city: 'Fresno', state: 'CA', population: 542107 },
  { city: 'Sacramento', state: 'CA', population: 513624 },
  { city: 'Kansas City', state: 'MO', population: 508090 },
  { city: 'Mesa', state: 'AZ', population: 504258 },
  { city: 'Atlanta', state: 'GA', population: 498715 },
  { city: 'Omaha', state: 'NE', population: 486051 },
  { city: 'Colorado Springs', state: 'CO', population: 478961 },
  { city: 'Raleigh', state: 'NC', population: 474069 },
  { city: 'Miami', state: 'FL', population: 467963 },
  { city: 'Long Beach', state: 'CA', population: 466742 },
  { city: 'Virginia Beach', state: 'VA', population: 459470 },
  { city: 'Oakland', state: 'CA', population: 425097 },
  { city: 'Minneapolis', state: 'MN', population: 429606 },
  { city: 'Tulsa', state: 'OK', population: 403505 },
  { city: 'Arlington', state: 'TX', population: 398112 },
  { city: 'Tampa', state: 'FL', population: 399700 },
  { city: 'New Orleans', state: 'LA', population: 390144 },
  { city: 'Wichita', state: 'KS', population: 397532 },
  { city: 'Cleveland', state: 'OH', population: 385479 },
  { city: 'Bakersfield', state: 'CA', population: 384692 },
  { city: 'Aurora', state: 'CO', population: 386312 },
  { city: 'Anaheim', state: 'CA', population: 350742 },
  { city: 'Honolulu', state: 'HI', population: 350964 },
  { city: 'Santa Ana', state: 'CA', population: 335072 },
  { city: 'Riverside', state: 'CA', population: 335176 },
  { city: 'Corpus Christi', state: 'TX', population: 327144 },
  { city: 'Lexington', state: 'KY', population: 322570 },
  { city: 'Stockton', state: 'CA', population: 322915 },
  { city: 'St. Louis', state: 'MO', population: 301578 },
  { city: 'St. Petersburg', state: 'FL', population: 258245 },
  { city: 'Henderson', state: 'NV', population: 317610 },
  { city: 'Pittsburgh', state: 'PA', population: 300286 },
  { city: 'Cincinnati', state: 'OH', population: 303825 },
  { city: 'Anchorage', state: 'AK', population: 291247 },
  { city: 'Greensboro', state: 'NC', population: 299035 },
  { city: 'Plano', state: 'TX', population: 285494 },
  { city: 'Newark', state: 'NJ', population: 282590 },
  { city: 'Lincoln', state: 'NE', population: 292657 },
  { city: 'Orlando', state: 'FL', population: 309416 },
  { city: 'Irvine', state: 'CA', population: 287401 },
  { city: 'Toledo', state: 'OH', population: 271455 },
  { city: 'Jersey City', state: 'NJ', population: 287829 },
  { city: 'Durham', state: 'NC', population: 283506 },
  { city: 'Chula Vista', state: 'CA', population: 274492 },
  { city: 'Fort Wayne', state: 'IN', population: 267833 },
  { city: 'Chandler', state: 'AZ', population: 261165 },
  { city: 'Lubbock', state: 'TX', population: 257918 },
  { city: 'Laredo', state: 'TX', population: 262904 },
  { city: 'Madison', state: 'WI', population: 269860 },
  { city: 'Reno', state: 'NV', population: 264165 },
  { city: 'St. Paul', state: 'MN', population: 308406 },
  { city: 'Buffalo', state: 'NY', population: 278349 },
  { city: 'Gilbert', state: 'AZ', population: 267009 },
  { city: 'Scottsdale', state: 'AZ', population: 257716 },
  { city: 'Birmingham', state: 'AL', population: 200356 },
  { city: 'Glendale', state: 'AZ', population: 252381 },
  { city: 'Norfolk', state: 'VA', population: 238147 },
  { city: 'Baton Rouge', state: 'LA', population: 220512 },
  { city: 'Boise', state: 'ID', population: 235684 },
  { city: 'North Las Vegas', state: 'NV', population: 262527 },
  { city: 'Chesapeake', state: 'VA', population: 244435 },
  { city: 'Spokane', state: 'WA', population: 228259 },
  { city: 'Rochester', state: 'NY', population: 210565 },
  { city: 'Des Moines', state: 'IA', population: 214237 },
  { city: 'Akron', state: 'OH', population: 190469 },
  { city: 'Fremont', state: 'CA', population: 230504 },
  { city: 'Richmond', state: 'VA', population: 230436 },
  { city: 'Yonkers', state: 'NY', population: 201344 },
  { city: 'San Bernardino', state: 'CA', population: 222070 },
  { city: 'Modesto', state: 'CA', population: 218464 },
  { city: 'Fayetteville', state: 'NC', population: 208501 },
  { city: 'Montgomery', state: 'AL', population: 198525 },
  { city: 'Huntington Beach', state: 'CA', population: 199003 },
  { city: 'Glendale', state: 'CA', population: 196436 },
  { city: 'Shreveport', state: 'LA', population: 187593 },
  { city: 'Amarillo', state: 'TX', population: 201421 },
  { city: 'Columbus', state: 'GA', population: 195769 },
  { city: 'Mobile', state: 'AL', population: 184952 },
  { city: 'Little Rock', state: 'AR', population: 198607 },
  { city: 'Knoxville', state: 'TN', population: 190740 },
  { city: 'Winston-Salem', state: 'NC', population: 247945 },
  { city: 'Augusta', state: 'GA', population: 202081 },
  { city: 'Tallahassee', state: 'FL', population: 197102 },
  { city: 'Providence', state: 'RI', population: 190934 },
  { city: 'Chattanooga', state: 'TN', population: 182799 },
  { city: 'Jackson', state: 'MS', population: 150340 },
  { city: 'Salt Lake City', state: 'UT', population: 199723 },
  { city: 'Ft. Lauderdale', state: 'FL', population: 182437 },
  { city: 'Grand Rapids', state: 'MI', population: 198917 },
  { city: 'Trenton', state: 'NJ', population: 84364 },
  { city: 'Columbus', state: 'OH', population: 898553 },
  { city: 'Cape Coral', state: 'FL', population: 194016 },
  { city: 'Sioux Falls', state: 'SD', population: 183027 },
  { city: 'Vancouver', state: 'WA', population: 186192 },
  { city: 'Brownsville', state: 'TX', population: 183049 },
  { city: 'Pompano Beach', state: 'FL', population: 111954 },
  { city: 'Huntsville', state: 'AL', population: 215006 },
  { city: 'Newport News', state: 'VA', population: 180419 },
  { city: 'Santa Clarita', state: 'CA', population: 228673 },
  { city: 'Savannah', state: 'GA', population: 147780 },
  { city: 'Port St. Lucie', state: 'FL', population: 204877 },
  { city: 'Provo', state: 'UT', population: 116618 },
  { city: 'Lakeland', state: 'FL', population: 112136 },
  { city: 'Killeen', state: 'TX', population: 153095 },
  { city: 'Syracuse', state: 'NY', population: 142749 },
  { city: 'Denton', state: 'TX', population: 139821 },
  { city: 'Frisco', state: 'TX', population: 200890 },
  { city: 'McKinney', state: 'TX', population: 199177 },
  { city: 'Round Rock', state: 'TX', population: 133372 },
  { city: 'Carrollton', state: 'TX', population: 133434 },
  { city: 'McAllen', state: 'TX', population: 142210 },
  { city: 'Waco', state: 'TX', population: 138183 },
  { city: 'Clearwater', state: 'FL', population: 116947 },
  { city: 'Lakewood', state: 'CO', population: 157070 },
  { city: 'Fort Collins', state: 'CO', population: 170243 },
  { city: 'Boulder', state: 'CO', population: 105420 },
  { city: 'Springfield', state: 'MO', population: 169176 },
  { city: 'Eugene', state: 'OR', population: 176654 },
  { city: 'Salem', state: 'OR', population: 174365 },
  { city: 'Pasadena', state: 'TX', population: 151950 },
  { city: 'Dayton', state: 'OH', population: 140540 },
  { city: 'Salem', state: 'MA', population: 43467 },
  { city: 'Concord', state: 'NC', population: 96240 },
  { city: 'Charleston', state: 'SC', population: 150227 },
  { city: 'Columbia', state: 'SC', population: 136632 },
  { city: 'Knoxville', state: 'TN', population: 190740 },
  { city: 'Asheville', state: 'NC', population: 94178 },
  { city: 'Greenville', state: 'SC', population: 70720 },
  { city: 'Sarasota', state: 'FL', population: 57520 },
  { city: 'Naples', state: 'FL', population: 22563 },
  { city: 'Gainesville', state: 'FL', population: 141085 },
  { city: 'Ocala', state: 'FL', population: 60989 },
  { city: 'Panama City', state: 'FL', population: 32939 },
  { city: 'Pensacola', state: 'FL', population: 52183 },
  { city: 'Tallahassee', state: 'FL', population: 197102 },
  { city: 'Boca Raton', state: 'FL', population: 99805 },
  { city: 'Delray Beach', state: 'FL', population: 68818 },
  { city: 'West Palm Beach', state: 'FL', population: 117415 },
  { city: 'Palm Beach Gardens', state: 'FL', population: 57128 },
  { city: 'Vero Beach', state: 'FL', population: 16119 },
  { city: 'Melbourne', state: 'FL', population: 83151 },
  { city: 'Titusville', state: 'FL', population: 48349 },
  { city: 'Daytona Beach', state: 'FL', population: 72647 },
  { city: 'Jacksonville Beach', state: 'FL', population: 23177 },
  { city: 'St. Augustine', state: 'FL', population: 15604 },
  { city: 'Palm Coast', state: 'FL', population: 92164 },
  { city: 'Port Orange', state: 'FL', population: 63679 },
  { city: 'Ormond Beach', state: 'FL', population: 43217 },
  { city: 'DeLand', state: 'FL', population: 38731 },
  { city: 'Sebastian', state: 'FL', population: 26441 },
  { city: 'Vero Beach South', state: 'FL', population: 20526 },
  { city: 'Fort Pierce', state: 'FL', population: 46603 },
  { city: 'Port St. Lucie', state: 'FL', population: 204877 },
  { city: 'Palm City', state: 'FL', population: 25120 },
  { city: 'Jensen Beach', state: 'FL', population: 12027 },
  { city: 'Stuart', state: 'FL', population: 17439 },
  { city: 'Hobe Sound', state: 'FL', population: 13311 },
  { city: 'Tequesta', state: 'FL', population: 6297 },
  { city: 'Jupiter', state: 'FL', population: 64735 },
  { city: 'Palm Beach', state: 'FL', population: 9245 },
  { city: 'Boynton Beach', state: 'FL', population: 80380 },
  { city: 'Greenacres', state: 'FL', population: 41421 },
  { city: 'Wellington', state: 'FL', population: 64527 },
  { city: 'Royal Palm Beach', state: 'FL', population: 38960 },
  { city: 'Loxahatchee', state: 'FL', population: 24618 },
  { city: 'Pahokee', state: 'FL', population: 5649 },
  { city: 'Belle Glade', state: 'FL', population: 16739 },
  { city: 'South Bay', state: 'FL', population: 5104 },
  { city: 'Clewiston', state: 'FL', population: 7227 },
  { city: 'Labelle', state: 'FL', population: 4961 },
  { city: 'Moore Haven', state: 'FL', population: 1684 },
];

// Group cities by state for the picker UI
export const CITIES_BY_STATE = US_CITIES.reduce((acc, c) => {
  if (!acc[c.state]) acc[c.state] = [];
  acc[c.state].push(c);
  return acc;
}, {});

export const US_STATES = Object.keys(CITIES_BY_STATE).sort();

// Top 50 metros by population (for quick selection)
export const TOP_50_METROS = US_CITIES
  .slice()
  .sort((a, b) => b.population - a.population)
  .slice(0, 50)
  .map(c => `${c.city}, ${c.state}`);