import { Link } from 'react-router-dom';
import { categories } from './serviceCatalog';
import ServiceVisual from './ServiceVisual';
import { BrainCircuit, Bot, MessagesSquare, Database, Megaphone, Search, Handshake, Globe, Blocks, GraduationCap, ShieldCheck, RefreshCw, ArrowUpRight } from 'lucide-react';

const icons = { strategy: BrainCircuit, automation: Bot, knowledge: MessagesSquare, data: Database, marketing: Megaphone, search: Search, crm: Handshake, websites: Globe, software: Blocks, training: GraduationCap, governance: ShieldCheck, managed: RefreshCw };

export default function ServiceDirectory() {
  return <section id="service-directory" className="agency-container scroll-mt-28 py-16 lg:py-24" aria-label="Full service directory">
    <div className="mb-10"><p className="agency-eyebrow mb-3">OUR SOLUTIONS</p><h2 className="mb-4 max-w-2xl font-heading text-3xl font-bold leading-tight tracking-tight text-foreground md:text-4xl">Practical AI for real-world business challenges.</h2><p className="max-w-2xl text-sm leading-relaxed">From the first opportunity assessment to a fully managed AI environment. Explore indicative starting prices; each engagement is scoped with you.</p></div>
    <nav aria-label="Service categories" className="mb-9 flex flex-wrap gap-2">{categories.map(group => <a key={group.id} href={`#${group.id}`} className="rounded border border-border bg-card px-3 py-2 text-xs font-medium text-foreground transition-colors hover:border-primary hover:text-primary focus-visible:outline focus-visible:outline-2 focus-visible:outline-primary">{group.title}</a>)}</nav>
    <div className="grid gap-5 lg:grid-cols-2">{categories.map((group, index) => { const Icon = icons[group.id]; return <article id={group.id} key={group.id} className="group flex scroll-mt-28 flex-col overflow-hidden rounded border border-border bg-card shadow-sm transition-colors hover:border-primary/40"><ServiceVisual index={index} /><div className="flex flex-1 flex-col p-6 md:p-8"><div className="mb-5 flex items-center justify-between"><span className="flex h-11 w-11 items-center justify-center rounded bg-muted text-primary"><Icon size={23} strokeWidth={1.8} /></span><ArrowUpRight size={17} className="text-primary" aria-hidden="true" /></div><h3 className="mb-2 text-xl font-bold">{group.title}</h3><p className="mb-6 text-sm leading-relaxed">{group.description}</p><ul className="mb-6 divide-y divide-border border-y border-border">{group.offers.map(([name, price]) => <li key={name} className="flex flex-wrap items-baseline justify-between gap-x-4 gap-y-1 py-3 text-sm"><span className="text-foreground">{name}</span><span className="font-semibold text-primary">{price}</span></li>)}</ul><Link to="/contact" className="mt-auto inline-flex items-center gap-2 text-sm font-semibold text-primary underline underline-offset-4">Discuss this service <ArrowUpRight size={16} /></Link></div></article>; })}</div>
    <p className="mt-8 text-xs text-muted-foreground">Prices are recommended starting points in USD, not a fixed quote. Scope, integrations, usage and ongoing support are confirmed in a proposal. Enterprise engagements are custom quoted.</p>
  </section>;
}