import { createClientFromRequest } from 'npm:@base44/sdk@0.8.52';
import { secrets } from 'base44:runtime';

// ============================================================
// PROVISION SITE — Full infrastructure provisioning pipeline
//
// Creates:
//   1. GitHub repo with site files pushed
//   2. Vercel project linked to the repo (auto-deploys on push)
//   3. Supabase project (free tier, only if needs_backend=true)
//
// Actions:
//   provision     — Full pipeline: GitHub → Vercel → (Supabase)
//   github_only   — Just create repo + push files
//   vercel_only   — Just create Vercel project for existing repo
//   supabase_only — Just create Supabase free-tier project
//   list          — List provisioned sites
//   get           — Get one provisioned site
//   delete        — Delete a provisioned site record
// ============================================================

function slugify(name: string): string {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 63);
}

async function providerError(res: Response, provider: string) {
  const data = await res.json().catch(() => ({}));
  throw new Error(`${provider}: ${data.error?.message || data.message || data.error || `request failed (${res.status})`}`);
}

// ── GitHub: Create repo ──
async function createGitHubRepo(accessToken: string, slug: string, description: string) {
  const res = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: { Authorization: `Bearer ${accessToken}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ name: slug, description, private: true, auto_init: true }),
  });
  if (!res.ok) await providerError(res, 'GitHub');
  return await res.json();
}

// ── GitHub: Push files via Git Data API ──
async function pushFilesToGitHub(accessToken: string, owner: string, repo: string, branch: string, files: Record<string, string>) {
  const headers = { Authorization: `Bearer ${accessToken}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' };

  // 1. Get the default branch ref
  const refRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`, { headers });
  if (!refRes.ok) await providerError(refRes, 'GitHub');
  const ref = await refRes.json();
  const commitSha = ref.object.sha;

  // 2. Get the commit to find its tree
  const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits/${commitSha}`, { headers });
  if (!commitRes.ok) await providerError(commitRes, 'GitHub');
  const commit = await commitRes.json();
  const baseTreeSha = commit.tree.sha;

  // 3. Create a new tree with all files
  const treeEntries = Object.entries(files).map(([path, content]) => ({
    path,
    mode: '100644',
    type: 'blob',
    content,
  }));

  const treeRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/trees`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ base_tree: baseTreeSha, tree: treeEntries }),
  });
  if (!treeRes.ok) await providerError(treeRes, 'GitHub');
  const tree = await treeRes.json();

  // 4. Create a commit
  const newCommitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits`, {
    method: 'POST',
    headers,
    body: JSON.stringify({ message: 'Initial site generated by Strategic Minds AI', tree: tree.sha, parents: [commitSha] }),
  });
  if (!newCommitRes.ok) await providerError(newCommitRes, 'GitHub');
  const newCommit = await newCommitRes.json();

  // 5. Update the ref
  const updateRefRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`, {
    method: 'PATCH',
    headers,
    body: JSON.stringify({ sha: newCommit.sha }),
  });
  if (!updateRefRes.ok) await providerError(updateRefRes, 'GitHub');

  return { commit_sha: newCommit.sha, file_count: Object.keys(files).length };
}

// ── Vercel: Create project ──
async function createVercelProject(slug: string, githubRepo: string) {
  const token = secrets.get('VERCEL_API_TOKEN');
  if (!token) throw new Error('VERCEL_API_TOKEN not configured');

  const res = await fetch('https://api.vercel.com/v11/projects', {
    method: 'POST',
    headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: slug,
      gitRepository: { type: 'github', repo: githubRepo },
      framework: null, // auto-detect
    }),
  });
  if (!res.ok) await providerError(res, 'Vercel');
  return await res.json();
}

// ── Vercel: Get project deployments ──
async function getVercelDeployments(projectId: string) {
  const token = secrets.get('VERCEL_API_TOKEN');
  const res = await fetch(`https://api.vercel.com/v6/deployments?projectId=${projectId}&limit=1`, {
    headers: { Authorization: `Bearer ${token}` },
  });
  if (!res.ok) return [];
  const data = await res.json();
  return data.deployments || [];
}

// ── Supabase: List organizations ──
async function listSupabaseOrgs(accessToken: string) {
  const res = await fetch('https://api.supabase.com/v1/organizations', {
    headers: { Authorization: `Bearer ${accessToken}` },
  });
  if (!res.ok) await providerError(res, 'Supabase');
  return await res.json();
}

// ── Supabase: Create free-tier project ──
async function createSupabaseProject(accessToken: string, name: string, orgId: string, region: string) {
  const dbPassword = crypto.randomUUID().replace(/-/g, '').slice(0, 16) + 'A1!';
  const res = await fetch('https://api.supabase.com/v1/projects', {
    method: 'POST',
    headers: { Authorization: `Bearer ${accessToken}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      name: name.toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 30),
      organization_id: orgId,
      plan: 'free',
      region,
      db_pass: dbPassword,
      kps_enabled: true,
    }),
  });
  if (!res.ok) await providerError(res, 'Supabase');
  return await res.json();
}

// ── Generate static site files ──
function generateStaticFiles(html: string, name: string): Record<string, string> {
  const slug = slugify(name);
  return {
    'index.html': html,
    'vercel.json': JSON.stringify({ name: slug, public: true, cleanUrls: true }, null, 2),
    'README.md': `# ${name}\n\nGenerated by Strategic Minds AI.\n`,
    '.gitignore': '.vercel\nnode_modules\n',
  };
}

// ── Generate Vite React files from BuildSpec ──
function generateViteFiles(buildSpec: any, projectName: string): Record<string, string> {
  const slug = slugify(projectName);
  const tokens = buildSpec?.tokens?.primitive || {};
  const primaryColor = tokens['color.primary.500'] || '#0066ff';

  const indexHtml = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<title>${projectName}</title>
</head>
<body>
<div id="root"></div>
<script type="module" src="/src/main.jsx"></script>
</body>
</html>`;

  const packageJson = JSON.stringify({
    name: slug, private: true, version: '0.0.1', type: 'module',
    scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' },
    dependencies: { react: '^18.2.0', 'react-dom': '^18.2.0' },
    devDependencies: { '@vitejs/plugin-react': '^4.2.0', vite: '^5.0.0', tailwindcss: '^3.4.0', postcss: '^8.4.0', autoprefixer: '^10.4.0' },
  }, null, 2);

  const viteConfig = `import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({\n  plugins: [react()],\n})`;
  const tailwindConfig = `/** @type {import('tailwindcss').Config} */\nexport default {\n  content: ['./index.html', './src/**/*.{js,jsx}'],\n  theme: { extend: { colors: { primary: '${primaryColor}' } },\n  },\n  plugins: [],\n}`;
  const postcssConfig = `export default {\n  plugins: { tailwindcss: {}, autoprefixer: {} },\n}`;
  const mainJsx = `import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App.jsx'\nimport './index.css'\n\nReactDOM.createRoot(document.getElementById('root')).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n)`;

  const screens = buildSpec?.screens || [];
  const navLinks = screens.map((s: any) => `<a href="${s.route}" className="hover:text-primary">${s.name}</a>`).join('\n            ');
  const featureCards = screens.slice(0, 3).map((s: any, i: number) => `          <div key={${i}} className="rounded-xl border border-gray-200 bg-white p-6">\n            <h2 className="text-xl font-semibold">${s.name}</h2>\n            <p className="mt-2 text-sm text-gray-600">${(s.content || []).join(' · ') || 'Content placeholder'}</p>\n          </div>`).join('\n');

  const appJsx = `import React from 'react'

export default function App() {
  return (
    <div className="min-h-screen bg-gray-50 text-gray-900">
      <header className="border-b border-gray-200 bg-white px-6 py-4">
        <nav className="mx-auto flex max-w-5xl items-center justify-between">
          <span className="text-lg font-bold text-primary">${projectName}</span>
          <div className="flex gap-6 text-sm text-gray-600">
            ${navLinks}
          </div>
        </nav>
      </header>
      <main className="mx-auto max-w-5xl px-6 py-12">
        <section className="mb-16 text-center">
          <h1 className="text-4xl font-bold text-gray-900">${projectName}</h1>
          <p className="mt-4 text-lg text-gray-600">Generated by Strategic Minds AI</p>
          <a href="/contact" className="mt-8 inline-block rounded-lg bg-primary px-6 py-3 text-white hover:opacity-90">Get Started</a>
        </section>
        <section className="grid grid-cols-1 gap-8 md:grid-cols-3">
${featureCards}
        </section>
      </main>
      <footer className="border-t border-gray-200 bg-white px-6 py-8 text-center text-sm text-gray-500">
        <p>&copy; ${new Date().getFullYear()} ${projectName}. All rights reserved.</p>
      </footer>
    </div>
  )
}`;

  const cssVars = Object.entries(tokens).filter(([k]) => k.startsWith('color.')).slice(0, 10).map(([k, v]) => `  --${k.replace(/\./g, '-')}: ${v};`).join('\n');
  const indexCss = `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n${cssVars}\n}`;

  return {
    'index.html': indexHtml,
    'package.json': packageJson,
    'vite.config.js': viteConfig,
    'tailwind.config.js': tailwindConfig,
    'postcss.config.js': postcssConfig,
    'src/main.jsx': mainJsx,
    'src/App.jsx': appJsx,
    'src/index.css': indexCss,
    'README.md': `# ${projectName}\n\nGenerated by Strategic Minds AI — UFF v${buildSpec?.registry_version || '2.0.0'}.\n`,
    '.gitignore': 'node_modules\ndist\n.env\n',
  };
}

export default async function(req: Request): Promise<Response> {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    if (user.role !== 'admin') return Response.json({ error: 'Admin only' }, { status: 403 });

    const svc = base44.asServiceRole;
    const body = await req.json().catch(() => ({}));
    const action = body.action || 'list';

    // ── provision (full pipeline) ──
    if (action === 'provision') {
      const { project_name, template_id, build_spec, custom_html, needs_backend, supabase_region } = body;
      if (!project_name) return Response.json({ error: 'project_name required' }, { status: 400 });

      const slug = slugify(project_name);
      const now = new Date().toISOString();

      // Create the ProvisionedSite record
      let site = await svc.entities.ProvisionedSite.create({
        project_name,
        slug,
        template_id: template_id || '',
        build_spec_id: build_spec?.project_id || '',
        site_type: custom_html || template_id ? 'static_html' : 'vite_react',
        needs_backend: !!needs_backend,
        supabase_region: supabase_region || 'us-east-1',
        supabase_plan: 'free',
        status: 'pending',
        progress_step: 'Starting provisioning pipeline',
        provisioned_at: now,
      });

      try {
        // Step 1: Get template content
        let htmlContent = '';
        let files: Record<string, string>;

        if (custom_html) {
          htmlContent = custom_html;
          files = generateStaticFiles(htmlContent, project_name);
          site = await svc.entities.ProvisionedSite.update(site.id, { progress_step: 'Using custom HTML' });
        } else if (template_id) {
          const template = await svc.entities.TemplateAsset.get(template_id);
          if (!template) throw new Error('Template not found');
          htmlContent = template.raw_content || '';
          files = generateStaticFiles(htmlContent, project_name);
          site = await svc.entities.ProvisionedSite.update(site.id, { progress_step: 'Using ingested template' });
        } else if (build_spec) {
          files = generateViteFiles(build_spec, project_name);
          site = await svc.entities.ProvisionedSite.update(site.id, { progress_step: 'Using UFF BuildSpec', site_type: 'vite_react' });
        } else {
          throw new Error('Provide template_id, build_spec, or custom_html');
        }

        // Step 2: Create GitHub repo
        site = await svc.entities.ProvisionedSite.update(site.id, { progress_step: 'Creating GitHub repository' });
        const { accessToken: ghToken } = await svc.connectors.getConnection('github');
        const repo = await createGitHubRepo(ghToken, slug, `Site generated by Strategic Minds AI — ${project_name}`);
        const owner = repo.owner.login;
        const repoFullName = repo.full_name;
        const branch = repo.default_branch || 'main';

        site = await svc.entities.ProvisionedSite.update(site.id, {
          github_repo: repoFullName,
          github_url: repo.html_url,
          github_default_branch: branch,
          status: 'github_created',
          progress_step: 'Pushing site files to GitHub',
        });

        // Step 3: Push files
        await pushFilesToGitHub(ghToken, owner, repo.name, branch, files);
        site = await svc.entities.ProvisionedSite.update(site.id, {
          status: 'files_pushed',
          progress_step: 'Creating Vercel project',
        });

        // Step 4: Create Vercel project
        const vercelProject = await createVercelProject(slug, repoFullName);
        site = await svc.entities.ProvisionedSite.update(site.id, {
          vercel_project_id: vercelProject.id,
          vercel_url: `https://vercel.com/${vercelProject.id}`,
          status: 'vercel_connected',
          progress_step: needs_backend ? 'Creating Supabase project' : 'Finalizing deployment',
        });

        // Step 5: Optional Supabase
        if (needs_backend) {
          try {
            const { accessToken: sbToken } = await svc.connectors.getConnection('supabase');
            const orgs = await listSupabaseOrgs(sbToken);
            if (!orgs || orgs.length === 0) throw new Error('No Supabase organizations found');
            const orgId = orgs[0].id;

            const sbProject = await createSupabaseProject(sbToken, slug, orgId, supabase_region || 'us-east-1');
            site = await svc.entities.ProvisionedSite.update(site.id, {
              supabase_project_id: sbProject.id,
              supabase_url: `https://${sbProject.id}.supabase.co`,
              status: 'supabase_created',
              progress_step: 'Supabase project created (free tier)',
            });
          } catch (sbErr: any) {
            // Supabase failure is non-fatal — site still deploys
            site = await svc.entities.ProvisionedSite.update(site.id, {
              progress_step: `Supabase skipped: ${sbErr.message}`,
            });
          }
        }

        // Final: Vercel auto-deploys on push. Try to get deployment URL.
        let deploymentUrl = '';
        try {
          // Wait a moment for Vercel to pick up the push
          await new Promise((r) => setTimeout(r, 3000));
          const deployments = await getVercelDeployments(vercelProject.id);
          if (deployments.length > 0) {
            deploymentUrl = deployments[0].url ? `https://${deployments[0].url}` : '';
          }
        } catch { /* deployment URL will populate later */ }

        site = await svc.entities.ProvisionedSite.update(site.id, {
          status: 'deployed',
          progress_step: 'Provisioning complete',
          vercel_deployment_url: deploymentUrl,
          deployment_url: deploymentUrl || `https://${slug}.vercel.app`,
          deployed_at: new Date().toISOString(),
        });

        return Response.json({ ok: true, site });
      } catch (err: any) {
        await svc.entities.ProvisionedSite.update(site.id, {
          status: 'failed',
          error: err.message,
          progress_step: 'Provisioning failed',
        });
        return Response.json({ error: err.message, site_id: site.id }, { status: 500 });
      }
    }

    // ── github_only ──
    if (action === 'github_only') {
      const { project_name, template_id, custom_html, build_spec } = body;
      if (!project_name) return Response.json({ error: 'project_name required' }, { status: 400 });

      const slug = slugify(project_name);
      let files: Record<string, string>;

      if (custom_html) {
        files = generateStaticFiles(custom_html, project_name);
      } else if (template_id) {
        const template = await svc.entities.TemplateAsset.get(template_id);
        if (!template) return Response.json({ error: 'Template not found' }, { status: 404 });
        files = generateStaticFiles(template.raw_content || '', project_name);
      } else if (build_spec) {
        files = generateViteFiles(build_spec, project_name);
      } else {
        return Response.json({ error: 'Provide template_id, build_spec, or custom_html' }, { status: 400 });
      }

      const { accessToken: ghToken } = await svc.connectors.getConnection('github');
      const repo = await createGitHubRepo(ghToken, slug, `Site — ${project_name}`);
      await pushFilesToGitHub(ghToken, repo.owner.login, repo.name, repo.default_branch || 'main', files);

      return Response.json({ ok: true, github_url: repo.html_url, github_repo: repo.full_name, file_count: Object.keys(files).length });
    }

    // ── supabase_only ──
    if (action === 'supabase_only') {
      const { project_name, region } = body;
      if (!project_name) return Response.json({ error: 'project_name required' }, { status: 400 });

      const { accessToken: sbToken } = await svc.connectors.getConnection('supabase');
      const orgs = await listSupabaseOrgs(sbToken);
      if (!orgs || orgs.length === 0) return Response.json({ error: 'No Supabase organizations found' }, { status: 400 });

      const slug = slugify(project_name).toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 30);
      const sbProject = await createSupabaseProject(sbToken, slug, orgs[0].id, region || 'us-east-1');

      return Response.json({ ok: true, supabase_id: sbProject.id, supabase_url: `https://${sbProject.id}.supabase.co` });
    }

    // ── list ──
    if (action === 'list') {
      const records = await svc.entities.ProvisionedSite.filter({}, { sort: '-created_date', limit: 100, fields: ['project_name', 'slug', 'status', 'github_url', 'vercel_deployment_url', 'supabase_url', 'deployment_url', 'needs_backend', 'created_date'] });
      return Response.json({ sites: records.items || [] });
    }

    // ── get ──
    if (action === 'get') {
      const { site_id } = body;
      if (!site_id) return Response.json({ error: 'site_id required' }, { status: 400 });
      const record = await svc.entities.ProvisionedSite.get(site_id);
      if (!record) return Response.json({ error: 'Site not found' }, { status: 404 });
      return Response.json({ site: record });
    }

    // ── delete ──
    if (action === 'delete') {
      const { site_id } = body;
      if (!site_id) return Response.json({ error: 'site_id required' }, { status: 400 });
      await svc.entities.ProvisionedSite.delete(site_id);
      return Response.json({ ok: true, deleted: site_id });
    }

    // ── refresh_deployment (check Vercel for deployment URL) ──
    if (action === 'refresh_deployment') {
      const { site_id } = body;
      if (!site_id) return Response.json({ error: 'site_id required' }, { status: 400 });
      const site = await svc.entities.ProvisionedSite.get(site_id);
      if (!site || !site.vercel_project_id) return Response.json({ error: 'Site or Vercel project not found' }, { status: 404 });

      const deployments = await getVercelDeployments(site.vercel_project_id);
      let deploymentUrl = '';
      if (deployments.length > 0 && deployments[0].url) {
        deploymentUrl = `https://${deployments[0].url}`;
      }

      if (deploymentUrl) {
        await svc.entities.ProvisionedSite.update(site_id, {
          vercel_deployment_url: deploymentUrl,
          deployment_url: deploymentUrl,
          status: 'deployed',
        });
      }

      return Response.json({ ok: true, deployment_url: deploymentUrl, deployments: deployments.length });
    }

    return Response.json({ error: `Unknown action: ${action}` }, { status: 400 });
  } catch (error: any) {
    console.error('Provision site error:', error.message);
    return Response.json({ error: error.message }, { status: 500 });
  }
}