import { createClientFromRequest } from 'npm:@base44/sdk@0.8.52';
import {
  slugify, createGitHubRepo, pushFilesToGitHub,
  createVercelProject, getVercelDeployments, listSupabaseOrgs, createSupabaseProject,
  generateStaticFiles, generateViteFiles
} from '../../shared/provisioning.ts';

// ============================================================
// PROVISION SITE — Full infrastructure provisioning pipeline
//
// Creates:
//   1. GitHub repo with site files pushed
//   2. Vercel project linked to the repo (auto-deploys on push)
//   3. Supabase project (free tier, only if needs_backend=true)
//
// Actions:
//   provision     — Full pipeline: GitHub → Vercel → (Supabase)
//   github_only   — Just create repo + push files
//   vercel_only   — Just create Vercel project for existing repo
//   supabase_only — Just create Supabase free-tier project
//   list          — List provisioned sites
//   get           — Get one provisioned site
//   delete        — Delete a provisioned site record
// ============================================================

export default async function(req: Request): Promise<Response> {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    if (user.role !== 'admin') return Response.json({ error: 'Admin only' }, { status: 403 });

    const svc = base44.asServiceRole;
    const body = await req.json().catch(() => ({}));
    const action = body.action || 'list';

    // ── provision (full pipeline) ──
    if (action === 'provision') {
      const { project_name, template_id, build_spec, custom_html, needs_backend, supabase_region } = body;
      if (!project_name) return Response.json({ error: 'project_name required' }, { status: 400 });

      const slug = slugify(project_name);
      const now = new Date().toISOString();

      // Create the ProvisionedSite record
      let site = await svc.entities.ProvisionedSite.create({
        project_name,
        slug,
        template_id: template_id || '',
        build_spec_id: build_spec?.project_id || '',
        site_type: custom_html || template_id ? 'static_html' : 'vite_react',
        needs_backend: !!needs_backend,
        supabase_region: supabase_region || 'us-east-1',
        supabase_plan: 'free',
        status: 'pending',
        progress_step: 'Starting provisioning pipeline',
        provisioned_at: now,
      });

      try {
        // Step 1: Get template content
        let htmlContent = '';
        let files: Record<string, string>;

        if (custom_html) {
          htmlContent = custom_html;
          files = generateStaticFiles(htmlContent, project_name);
          site = await svc.entities.ProvisionedSite.update(site.id, { progress_step: 'Using custom HTML' });
        } else if (template_id) {
          const template = await svc.entities.TemplateAsset.get(template_id);
          if (!template) throw new Error('Template not found');
          htmlContent = template.raw_content || '';
          files = generateStaticFiles(htmlContent, project_name);
          site = await svc.entities.ProvisionedSite.update(site.id, { progress_step: 'Using ingested template' });
        } else if (build_spec) {
          files = generateViteFiles(project_name);
          site = await svc.entities.ProvisionedSite.update(site.id, { progress_step: 'Using UFF BuildSpec', site_type: 'vite_react' });
        } else {
          throw new Error('Provide template_id, build_spec, or custom_html');
        }

        // Step 2: Create GitHub repo
        site = await svc.entities.ProvisionedSite.update(site.id, { progress_step: 'Creating GitHub repository' });
        const { accessToken: ghToken } = await svc.connectors.getConnection('github');
        const repo = await createGitHubRepo(ghToken, slug, `Site generated by Strategic Minds AI — ${project_name}`);
        const owner = repo.owner.login;
        const repoFullName = repo.full_name;
        const branch = repo.default_branch || 'main';

        site = await svc.entities.ProvisionedSite.update(site.id, {
          github_repo: repoFullName,
          github_url: repo.html_url,
          github_default_branch: branch,
          status: 'github_created',
          progress_step: 'Pushing site files to GitHub',
        });

        // Step 3: Push files
        await pushFilesToGitHub(ghToken, owner, repo.name, branch, files);
        site = await svc.entities.ProvisionedSite.update(site.id, {
          status: 'files_pushed',
          progress_step: 'Creating Vercel project',
        });

        // Step 4: Create Vercel project
        const vercelProject = await createVercelProject(slug, repoFullName);
        site = await svc.entities.ProvisionedSite.update(site.id, {
          vercel_project_id: vercelProject.id,
          vercel_url: `https://vercel.com/${vercelProject.id}`,
          status: 'vercel_connected',
          progress_step: needs_backend ? 'Creating Supabase project' : 'Finalizing deployment',
        });

        // Step 5: Optional Supabase
        if (needs_backend) {
          try {
            const { accessToken: sbToken } = await svc.connectors.getConnection('supabase');
            const orgs = await listSupabaseOrgs(sbToken);
            if (!orgs || orgs.length === 0) throw new Error('No Supabase organizations found');
            const orgId = orgs[0].id;

            const sbProject = await createSupabaseProject(sbToken, slug, orgId, supabase_region || 'us-east-1');
            site = await svc.entities.ProvisionedSite.update(site.id, {
              supabase_project_id: sbProject.id,
              supabase_url: `https://${sbProject.id}.supabase.co`,
              status: 'supabase_created',
              progress_step: 'Supabase project created (free tier)',
            });
          } catch (sbErr: any) {
            // Supabase failure is non-fatal — site still deploys
            site = await svc.entities.ProvisionedSite.update(site.id, {
              progress_step: `Supabase skipped: ${sbErr.message}`,
            });
          }
        }

        // Final: Vercel auto-deploys on push. Try to get deployment URL.
        let deploymentUrl = '';
        try {
          await new Promise((r) => setTimeout(r, 3000));
          const deployments = await getVercelDeployments(vercelProject.id);
          if (deployments.length > 0) {
            deploymentUrl = deployments[0].url ? `https://${deployments[0].url}` : '';
          }
        } catch { /* deployment URL will populate later */ }

        site = await svc.entities.ProvisionedSite.update(site.id, {
          status: 'deployed',
          progress_step: 'Provisioning complete',
          vercel_deployment_url: deploymentUrl,
          deployment_url: deploymentUrl || `https://${slug}.vercel.app`,
          deployed_at: new Date().toISOString(),
        });

        return Response.json({ ok: true, site });
      } catch (err: any) {
        await svc.entities.ProvisionedSite.update(site.id, {
          status: 'failed',
          error: err.message,
          progress_step: 'Provisioning failed',
        });
        return Response.json({ error: err.message, site_id: site.id }, { status: 500 });
      }
    }

    // ── github_only ──
    if (action === 'github_only') {
      const { project_name, template_id, custom_html, build_spec } = body;
      if (!project_name) return Response.json({ error: 'project_name required' }, { status: 400 });

      const slug = slugify(project_name);
      let files: Record<string, string>;

      if (custom_html) {
        files = generateStaticFiles(custom_html, project_name);
      } else if (template_id) {
        const template = await svc.entities.TemplateAsset.get(template_id);
        if (!template) return Response.json({ error: 'Template not found' }, { status: 404 });
        files = generateStaticFiles(template.raw_content || '', project_name);
      } else if (build_spec) {
        files = generateViteFiles(project_name);
      } else {
        return Response.json({ error: 'Provide template_id, build_spec, or custom_html' }, { status: 400 });
      }

      const { accessToken: ghToken } = await svc.connectors.getConnection('github');
      const repo = await createGitHubRepo(ghToken, slug, `Site — ${project_name}`);
      await pushFilesToGitHub(ghToken, repo.owner.login, repo.name, repo.default_branch || 'main', files);

      return Response.json({ ok: true, github_url: repo.html_url, github_repo: repo.full_name, file_count: Object.keys(files).length });
    }

    // ── supabase_only ──
    if (action === 'supabase_only') {
      const { project_name, region } = body;
      if (!project_name) return Response.json({ error: 'project_name required' }, { status: 400 });

      const { accessToken: sbToken } = await svc.connectors.getConnection('supabase');
      const orgs = await listSupabaseOrgs(sbToken);
      if (!orgs || orgs.length === 0) return Response.json({ error: 'No Supabase organizations found' }, { status: 400 });

      const slug = slugify(project_name).toLowerCase().replace(/[^a-z0-9]/g, '').slice(0, 30);
      const sbProject = await createSupabaseProject(sbToken, slug, orgs[0].id, region || 'us-east-1');

      return Response.json({ ok: true, supabase_id: sbProject.id, supabase_url: `https://${sbProject.id}.supabase.co` });
    }

    // ── list ──
    if (action === 'list') {
      const records = await svc.entities.ProvisionedSite.filter({}, { sort: '-created_date', limit: 100, fields: ['project_name', 'slug', 'status', 'github_url', 'vercel_deployment_url', 'supabase_url', 'deployment_url', 'needs_backend', 'created_date'] });
      return Response.json({ sites: records.items || [] });
    }

    // ── get ──
    if (action === 'get') {
      const { site_id } = body;
      if (!site_id) return Response.json({ error: 'site_id required' }, { status: 400 });
      const record = await svc.entities.ProvisionedSite.get(site_id);
      if (!record) return Response.json({ error: 'Site not found' }, { status: 404 });
      return Response.json({ site: record });
    }

    // ── delete ──
    if (action === 'delete') {
      const { site_id } = body;
      if (!site_id) return Response.json({ error: 'site_id required' }, { status: 400 });
      await svc.entities.ProvisionedSite.delete(site_id);
      return Response.json({ ok: true, deleted: site_id });
    }

    // ── refresh_deployment (check Vercel for deployment URL) ──
    if (action === 'refresh_deployment') {
      const { site_id } = body;
      if (!site_id) return Response.json({ error: 'site_id required' }, { status: 400 });
      const site = await svc.entities.ProvisionedSite.get(site_id);
      if (!site || !site.vercel_project_id) return Response.json({ error: 'Site or Vercel project not found' }, { status: 404 });

      const deployments = await getVercelDeployments(site.vercel_project_id);
      let deploymentUrl = '';
      if (deployments.length > 0 && deployments[0].url) {
        deploymentUrl = `https://${deployments[0].url}`;
      }

      if (deploymentUrl) {
        await svc.entities.ProvisionedSite.update(site_id, {
          vercel_deployment_url: deploymentUrl,
          deployment_url: deploymentUrl,
          status: 'deployed',
        });
      }

      return Response.json({ ok: true, deployment_url: deploymentUrl, deployments: deployments.length });
    }

    return Response.json({ error: `Unknown action: ${action}` }, { status: 400 });
  } catch (error: any) {
    console.error('Provision site error:', error.message);
    return Response.json({ error: error.message }, { status: 500 });
  }
}