import { useState } from 'react';
import { LockKeyhole, Copy, Check, ArrowUpRight, Plug } from 'lucide-react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { handoffText } from '@/components/swarm/swarmActions';
export default function ConnectionsDialog({ open, onOpenChange, run }) {
  const [copied, setCopied] = useState(false), [error, setError] = useState('');
  async function copy() { try { await navigator.clipboard.writeText(handoffText(run)); setCopied(true); } catch { setError('Clipboard unavailable. Select and copy the handoff text below.'); } }
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-w-xl max-h-[85dvh] overflow-y-auto bg-background">
    <DialogHeader><div className="mb-3 flex h-10 w-10 items-center justify-center rounded-md border border-primary/20 bg-primary/10 text-primary"><Plug size={20}/></div><DialogTitle className="text-2xl">Connect your AI workspace</DialogTitle><DialogDescription>Let ChatGPT work with your swarms through MCP.</DialogDescription></DialogHeader>
    <div className="flex items-center gap-2 rounded-md border bg-card p-3 text-xs"><LockKeyhole size={15} className="text-primary"/><span>Sign-in required · OAuth</span><span className="ml-auto text-muted-foreground">Configured</span></div>
    <ol className="space-y-5 py-3 text-sm list-decimal pl-5 marker:text-primary"><li className="pl-1"><strong className="font-medium">Publish this app</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">In the Base44 builder, publish the app, then copy the exact endpoint from this app’s MCP page. Preview addresses are not live MCP endpoints.</p></li><li className="pl-1"><strong className="font-medium">Add it to ChatGPT</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">On a supported ChatGPT plan, enable Developer mode under Apps, choose Create app, and paste the MCP endpoint. Review the risk warning: connected tools may read and change your data.</p></li><li className="pl-1"><strong className="font-medium">Sign in and approve</strong><p className="mt-1 text-xs leading-5 text-muted-foreground">Use your account for this app and review the consent screen. Select this app in the ChatGPT composer before asking it to work on a saved swarm.</p></li></ol>
    {run && <div className="rounded-md border bg-card p-3"><div className="mb-2 flex items-center justify-between"><span className="text-xs font-medium">Handoff this run</span><button onClick={copy} className="flex items-center gap-1 text-xs text-primary">{copied ? <Check size={13}/> : <Copy size={13}/>} {copied ? 'Copied' : 'Copy prompt'}</button></div><textarea aria-label="ChatGPT handoff prompt" readOnly value={handoffText(run)} className="h-28 w-full resize-none rounded border bg-background p-2 font-mono text-xs leading-5"/>{error && <p role="alert" className="mt-2 text-xs text-destructive">{error}</p>}</div>}
    <div className="space-y-2 text-xs leading-5 text-muted-foreground"><p>MCP exposes this app’s runs, task records and four native agent tools, subject to your permissions. Owners can disable individual tools on the MCP page. Refresh and reauthorize clients after publishing tool changes.</p><p>ChatGPT controls its own runtime and permissions. This app does not inherit your subscription, other connected apps, or unlimited usage. Native agent calls consume Base44 credits.</p><p>OpenFang hosting, its autonomous Hands and an execution sandbox require a separate runtime connection.</p></div>
    <a className="flex items-center gap-1 text-xs text-primary" href="https://help.openai.com/en/articles/12584461-developer-mode-and-mcp-apps-in-chatgpt" target="_blank" rel="noreferrer">ChatGPT MCP requirements<ArrowUpRight size={13}/></a>
  </DialogContent></Dialog>;
}