import { Activity, ArrowUpRight, Globe, Terminal, Network, ShieldCheck, Clock3, ChevronRight } from 'lucide-react';
export default function RuntimePanel({ swarm: s, onConnect }) {
  const completed = s.tasks.filter(t => t.status === 'completed').length;
  return <aside className="flex h-full w-full flex-col bg-sidebar xl:w-[320px]">
    <div className="flex h-16 items-center justify-between border-b px-5"><span className="flex items-center gap-2 text-xs font-medium"><Activity size={14} className="text-primary"/>Runtime overview</span><span className="font-mono text-[9px] text-muted-foreground">MCP / 01</span></div>
    <div className="flex-1 space-y-7 overflow-y-auto p-5">
      <section><div className="mb-4 flex items-center justify-between"><h2 className="swarm-label">Tool ecosystem</h2><button onClick={onConnect} aria-label="Configure tool connections" className="text-muted-foreground hover:text-primary"><ArrowUpRight size={14}/></button></div>
        <div className="space-y-1 rounded-md border bg-card p-1">{[[Network,'ChatGPT','External client'],[Globe,'Web search','Built in'],[Terminal,'Code sandbox','Not connected'],[Network,'OpenFang runtime','Not connected']].map(([Icon,name,status]) => <div key={name} className="flex items-center gap-2.5 rounded px-2 py-3"><Icon size={15} className="text-muted-foreground"/><span className="flex-1 text-xs">{name}</span><span className={`flex items-center gap-1 text-[9px] ${status === 'Built in' ? 'text-primary' : 'text-muted-foreground'}`}><span className={`h-1 w-1 rounded-full ${status === 'Built in' ? 'bg-primary' : 'bg-muted-foreground'}`}/>{status}</span></div>)}</div>
        <button onClick={onConnect} className="mt-3 flex w-full items-center justify-between rounded-md border border-dashed px-3 py-2.5 text-xs text-muted-foreground hover:border-primary/50 hover:text-foreground">Connect through MCP<ChevronRight size={13}/></button>
      </section>
      <section><h2 className="swarm-label mb-4">Run telemetry</h2><div className="grid grid-cols-2 gap-3"><div className="rounded-md border bg-card p-3"><p className="text-[10px] text-muted-foreground">Selected agents</p><p className="mt-2 font-mono text-xl">{s.run?.agent_ids?.length || s.selected.length}<span className="ml-1 text-xs text-muted-foreground">/ 30</span></p></div><div className="rounded-md border bg-card p-3"><p className="text-[10px] text-muted-foreground">Dispatch limit</p><p className="mt-2 font-mono text-xl">{s.run?.concurrency || s.concurrency}<span className="ml-1 text-xs text-muted-foreground">parallel</span></p></div></div><div className="mt-4 flex justify-between text-xs"><span className="text-muted-foreground">Token consumption</span><span className="font-mono">—</span></div><div className="mt-2 flex gap-1" aria-hidden="true">{Array.from({length:28},(_,i) => <span key={i} className="h-3 flex-1 rounded-sm bg-secondary"/>)}</div><p className="mt-2 text-[10px] leading-4 text-muted-foreground">Token usage is not reported by this runtime. No estimates are shown.</p></section>
      <section><div className="mb-4 flex items-center justify-between"><h2 className="swarm-label">Context stream</h2><span className="text-[9px] text-muted-foreground">{s.tasks.length ? 'Synced records' : 'Awaiting run'}</span></div><div className="space-y-4 border-l border-border ml-1 pl-4">{s.tasks.length ? s.tasks.map(t => <div key={t.id} className="relative"><span className={`absolute -left-[21px] top-1.5 h-2 w-2 rounded-full border-2 border-sidebar ${t.status === 'error' ? 'bg-destructive' : t.status === 'completed' ? 'bg-primary' : 'bg-accent'}`}/><p className="font-mono text-[10px] text-muted-foreground">{new Date(t.updated_at || t.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})}</p><p className="mt-1 text-xs">{t.agent_name}</p><p className="mt-1 font-mono text-[10px] text-muted-foreground">{t.status.replaceAll('_',' ')}</p></div>) : <div><Clock3 size={16} className="mb-3 text-muted-foreground"/><p className="text-xs">Ready for your first objective</p><p className="mt-2 text-[11px] leading-5 text-muted-foreground">Agent dispatches and task updates will appear here as they happen.</p></div>}</div>{completed > 0 && <p className="mt-4 text-xs text-primary">{completed} tasks marked complete</p>}</section>
    </div>
    <div className="flex items-center gap-2 border-t px-5 py-4 text-[10px] text-muted-foreground"><ShieldCheck size={13} className="text-primary"/>OAuth protected<span className="ml-auto">Your data. Your control.</span></div>
  </aside>;
}