export const configuredSurfaces = [
  { id: 'mobile.whatsapp', provider: 'Agency WhatsApp channel', category: 'mobile', name: 'WhatsApp planning assistant and account-saved conversations', tool: 'admin_phone', availability: 'PARTIAL', auth: 'operator_channel_pairing_not_verified', reason: 'Channel connect link and in-app conversation UI implemented. Real phone pairing and cross-channel visibility remain unverified. No computer or terminal permissions granted.', source: 'admin_phone configuration and Phone & WhatsApp admin view' },
  { id: 'google.docs', provider: 'Google Docs', category: 'documents', name: 'Document API authorization', tool: null, availability: 'PARTIAL', auth: 'shared_connector_authorized_at_discovery', reason: 'Documents scope authorized; no document-specific read or edit tested and no generalized document editor discovered.', source: 'Connector authorization discovery; document runtime not tested' },
  { id: 'google.sheets', provider: 'Google Sheets', category: 'spreadsheets', name: 'Spreadsheet API authorization', tool: null, availability: 'PARTIAL', auth: 'shared_connector_authorized_at_discovery', reason: 'Spreadsheets scope authorized; no spreadsheet-specific read or edit tested and no generalized spreadsheet editor discovered.', source: 'Connector authorization discovery; spreadsheet runtime not tested' },
  { id: 'google.drive.writes', provider: 'Google Drive', category: 'files', name: 'Existing folder, upload and project-deliverable flows', tool: 'agencyDriveIngest', availability: 'PARTIAL', auth: 'shared_connector_authorized_at_discovery', reason: 'Implementation and Drive authorization found. Writes, sharing and canonical folder migration were not executed or certified.', source: 'agencyDriveIngest implementation and connector authorization discovery' },
  { id: 'chat.standard', provider: 'Vercel AI Gateway', category: 'chat', name: 'Existing text assistant', tool: 'adminAssistant', availability: 'PARTIAL', reason: 'Code inspected: non-streaming chat completions; no tool execution.', source: 'adminAssistant implementation' },
  { id: 'chat.history', provider: 'Agency console', category: 'memory', name: 'Conversation persistence', tool: null, availability: 'PARTIAL', reason: 'Browser-local history only; cross-device runtime storage is not implemented.', source: 'AdminChatWorkspace implementation' },
  { id: 'chat.web_files', provider: 'Core integrations', category: 'multimodal', name: 'Web-assisted answers and attachment analysis', tool: 'InvokeLLM', availability: 'PARTIAL', reason: 'Implementation found; no inference request made during discovery.', source: 'adminChatActions implementation' },
  { id: 'chat.images', provider: 'Core integrations', category: 'images', name: 'Image generation', tool: 'GenerateImage', availability: 'PARTIAL', reason: 'Implementation found; no billable generation performed.', source: 'adminChatActions implementation' },
  { id: 'openai.responses', provider: 'OpenAI', category: 'chat', name: 'Direct Responses API', tool: null, availability: 'MISSING_PERMISSION', reason: 'No direct OpenAI credential configured in the supplied secret inventory.', source: 'Supplied app secret inventory' },
  { id: 'openai.tools', provider: 'OpenAI', category: 'tools', name: 'Responses streaming, reasoning, structured outputs, MCP, search and background tools', tool: null, availability: 'UNKNOWN', reason: 'Documented provider features are not proof of account authorization or model compatibility.', source: 'Provider documentation; account entitlements not inspected' },
  { id: 'openai.voice', provider: 'OpenAI', category: 'audio', name: 'Realtime voice, speech and audio', tool: null, availability: 'UNKNOWN', reason: 'No authorized voice session or runtime implementation discovered.', source: 'Console source inspection' },
  { id: 'mcp.agency', provider: 'Agency console', category: 'mcp', name: 'Agency MCP server', tool: 'vault_directory', availability: 'PARTIAL', reason: 'OAuth configuration exists; authenticated tools/list and published exposure not verified.', source: 'Agency MCP configuration' },
  { id: 'mcp.external', provider: 'External providers', category: 'mcp', name: 'External MCP registry and routing', tool: null, availability: 'MISSING_CONNECTOR', reason: 'No external endpoint or authenticated tool inventory supplied.', source: 'Console source and supplied connector inventory' },
  { id: 'skills.runtime', provider: 'Agency console', category: 'skills', name: 'Runtime skill discovery and selection', tool: null, availability: 'MISSING_TOOL', reason: 'Builder workspace skills and five project skill references are not deployed runtime tools.', source: 'Workspace builder catalog and project skill inventory' },
  { id: 'plugins.runtime', provider: 'ChatGPT', category: 'plugins', name: 'Installed plugin inventory', tool: null, availability: 'UNKNOWN', reason: 'Operator reports 4,437 tools across 58 namespaces; no authenticated export supplied.', source: 'Operator-provided initial inventory; not independently verified' },
  { id: 'worker.browser', provider: 'Cloud Browser', category: 'browser', name: 'Isolated browser execution', tool: null, availability: 'MISSING_CONNECTOR', reason: 'No authenticated browser worker endpoint configured.', source: 'Console source inspection' },
  { id: 'worker.computer', provider: 'Remote Desktop Commander', category: 'computer', name: 'Background computer execution', tool: null, availability: 'MISSING_CONNECTOR', reason: 'Reported in external ChatGPT inventory only; no console execution bridge or authorization discovered.', source: 'Operator report and console source inspection' },
  { id: 'worker.phone', provider: 'Phone bridge', category: 'mobile', name: 'Phone connection / remote control', tool: null, availability: 'MISSING_CONNECTOR', reason: 'No authenticated phone bridge discovered; requested remove/remote behavior requires clarification.', source: 'Console source inspection and operator request' },
  { id: 'apex.queue', provider: 'APEX', category: 'execution', name: 'Durable queue, leasing and worker recovery', tool: null, availability: 'MISSING_TOOL', reason: 'No durable work-packet runtime found.', source: 'Console source inspection' },
  { id: 'apex.governance', provider: 'APEX', category: 'governance', name: 'Unified approvals, receipts and independent validation', tool: null, availability: 'MISSING_TOOL', reason: 'Not implemented; existing explicit action buttons do not constitute a central approval gate.', source: 'Console source inspection' },
  { id: 'apex.reconcile', provider: 'APEX', category: 'workflows', name: 'Five-minute reconciliation heartbeat', tool: null, availability: 'MISSING_TOOL', reason: 'No APEX heartbeat found. Existing CRM schedule is separate and remains unchanged.', source: 'Workflow inventory' },
  { id: 'mobile.pwa', provider: 'Agency console', category: 'mobile', name: 'Installable PWA and cross-device continuity', tool: null, availability: 'MISSING_TOOL', reason: 'Responsive console exists; no app manifest, service worker or synchronized chat runtime discovered.', source: 'Console source inspection' },
  { id: 'google.gmail.modify', provider: 'Gmail', category: 'communications', name: 'Drafts, labels and archive', tool: null, availability: 'MISSING_PERMISSION', reason: 'Current shared scopes are readonly and send; compose/modify/labels are not authorized.', source: 'Connector authorization discovery' },
  { id: 'google.slides', provider: 'Google Slides', category: 'documents', name: 'Presentation editing', tool: null, availability: 'MISSING_CONNECTOR', reason: 'No Slides connector authorization supplied; Drive authorization is not Slides API authorization.', source: 'Supplied connector inventory' },
  { id: 'workflow.crm', provider: 'Agency console', category: 'workflows', name: 'Existing CRM follow-up schedule', tool: 'crmFollowUps', availability: 'PARTIAL', reason: 'Active every 15 minutes at discovery; no run success or unified approval boundary certified.', source: 'Workflow status discovery at 2026-09-29T17:32:52Z; not rechecked by runtime discovery' },
  { id: 'workflow.forms', provider: 'Agency console', category: 'workflows', name: 'Existing form-email workflows', tool: 'send-form-emails', availability: 'PARTIAL', reason: 'Six workflows inactive at discovery; no activation performed.', source: 'Workflow status discovery at 2026-09-29T17:32:52Z; not rechecked by runtime discovery' }
];
export function capabilityRecord(item: any, verifiedAt: string | null = null) {
  return { capability_id: item.id, provider: item.provider, category: item.category, capability_name: item.name, tool_name: item.tool || null, namespace: item.namespace || null, skill_name: null, availability: item.availability, read_write_capability: item.access || 'not_verified', authentication_status: item.auth || 'unknown', permission_boundary: item.boundary || 'No execution granted by this discovery record', approval_requirement: item.approval || 'Protected actions require explicit operator approval', environment: 'agency_admin', last_verified_at: verifiedAt, validation_status: item.validation || 'NOT_EXECUTION_VALIDATED', health_status: item.health || 'Unknown', failure_reason: item.reason || null, fallback: item.fallback || 'Block execution until the required authorization and capability are verified', source_of_truth: item.source };
}