export const BENCHMARK_VERSION = '2026-09-29.1';
export const sources = [
  { id: 'g2.awards', publisher: 'G2', title: '2026 Best Agentic AI Software Products', url: 'https://www.g2.com/best-software-companies/top-agentic-ai', observed_on: '2026-09-29', evidence: 'Salesforce Agentforce ranked 1; Fin ranked 2. Annual award ranking, not a universal highest-star-rating ranking.' },
  { id: 'sf.multi', publisher: 'Salesforce', title: 'Multi-Agent Orchestration', url: 'https://www.salesforce.com/agentforce/multi-agent-orchestration/', observed_on: '2026-09-29', evidence: 'Primary and specialist agents, delegated tasks, A2A collaboration, governance and observability.' },
  { id: 'sf.interop', publisher: 'Salesforce', title: 'Agentforce Interoperability Guide', url: 'https://www.salesforce.com/agentforce/resources/interoperability-guide/', observed_on: '2026-09-29', evidence: 'Single-org and multi-org agent orchestration; external agents and MCP tools. Not proof of unlimited autonomous swarms.' },
  { id: 'sf.test', publisher: 'Salesforce', title: 'Testing Center: Agent Evaluation', url: 'https://www.salesforce.com/blog/agentforce-testing-center-usecase-blog/', observed_on: '2026-09-29', evidence: 'Ground-truth evaluation, topic/action/response testing, repeatable testing and CI/CD integration.' },
  { id: 'sf.marketing', publisher: 'Salesforce', title: 'Marketing Cloud', url: 'https://www.salesforce.com/marketing/', observed_on: '2026-09-29', evidence: 'Customer engagement and marketing platform. Edition-specific capabilities require separate verification.' },
  { id: 'sf.leads', publisher: 'Salesforce', title: 'Lead Generation Tools', url: 'https://www.salesforce.com/marketing/lead-generation-guide/best-lead-generation-tools/', observed_on: '2026-09-29', evidence: 'Lead generation, qualification, nurturing, predictive scoring and automated workflows.' },
  { id: 'sf.price', publisher: 'Salesforce', title: 'Agentforce Pricing', url: 'https://www.salesforce.com/agentforce/pricing/', observed_on: '2026-09-29', evidence: 'Multiple buying models, including $500 per 100,000 Flex Credits and $2 conversations; other licenses and edition costs apply.' },
  { id: 'fin.cap', publisher: 'Fin', title: 'Fin Capabilities', url: 'https://fin.ai/capabilities', observed_on: '2026-09-29', evidence: 'Procedures, knowledge sources, data connectors, guidance, simulations, channel deployment and insights.' },
  { id: 'fin.test', publisher: 'Fin', title: 'Eval-Driven Delivery', url: 'https://fin.ai/testing', observed_on: '2026-09-29', evidence: 'Scenario evaluations, distinct customer and judge roles, regression suites, releases, A/B testing, monitoring, rollback and Operator-assisted improvement.' },
  { id: 'fin.sales', publisher: 'Intercom', title: 'Fin for Sales FAQs', url: 'https://www.intercom.com/help/en/articles/13927115-fin-for-sales-faqs', observed_on: '2026-09-29', evidence: 'Lead qualification and routing; CRM/GTM connections including Salesforce, HubSpot, Marketo and Chili Piper.' },
  { id: 'fin.content', publisher: 'Intercom', title: 'Add Content for Fin', url: 'https://www.intercom.com/help/en/articles/7837514-add-your-content-for-fin-ai-agent', observed_on: '2026-09-29', evidence: 'Public and private content, source sync status, content import errors and knowledge management. Not proof of every Google service integration.' },
  { id: 'fin.price', publisher: 'Intercom', title: 'Fin Outcomes', url: 'https://www.intercom.com/help/en/articles/8205718-fin-ai-agent-outcomes', observed_on: '2026-09-29', evidence: '$0.99 resolutions/procedure handoffs and $9.99 qualifications in the documented Intercom sales pricing; seats, channels and agreements can add costs.' }
];
export const competitors = [
  { id: 'salesforce', company: 'Salesforce', product: 'Agentforce', rank: 1, ranking_source: 'g2.awards', focus: 'Enterprise agent orchestration and the wider Salesforce CRM, sales and marketing ecosystem.', strengths: ['Primary-to-specialist delegation and A2A', 'Enterprise governance and observability', 'Ground-truth evaluation and CI/CD'], limits: 'A broad platform requiring configuration, editions and integrations. The award does not certify every feature or every Google integration.', pricing: '$500 / 100,000 Flex Credits; other models and platform licenses apply.', source_ids: ['sf.multi', 'sf.interop', 'sf.test', 'sf.marketing', 'sf.leads', 'sf.price'] },
  { id: 'fin', company: 'Fin / Intercom ecosystem', product: 'Fin', rank: 2, ranking_source: 'g2.awards', focus: 'Autonomous customer support, sales qualification and controlled continuous improvement.', strengths: ['Train → test → deploy → analyze lifecycle', 'Procedures, data connectors and multichannel support', 'Independent judge roles, release testing and rollback'], limits: 'Not evidenced as a general-purpose autonomous swarm or coding-worker platform. Full Salesforce-style marketing-suite parity is not established.', pricing: '$0.99 resolutions; documented sales qualifications $9.99; other charges apply.', source_ids: ['fin.cap', 'fin.test', 'fin.sales', 'fin.content', 'fin.price'] }
];
export const selectionPolicy = 'The first two products in G2’s 2026 Best Agentic AI Software Products awards were selected. This is a published category ranking, not a claim that two companies are highest-rated across all enterprise, CRM and swarm categories. Vendor documentation is evidence of advertised capabilities, not independently executed competitor tests. User-requested extensions are labeled separately.';