import { useState } from 'react';
import { useAuth } from '@/lib/AuthContext';
import PhoneConnectionLinks from '@/components/portal/phone/PhoneConnectionLinks';
import PhoneAgentMessages from '@/components/portal/phone/PhoneAgentMessages';
import usePhoneChat from '@/components/portal/phone/usePhoneChat';
export default function AdminPhoneLink() {
  const { user } = useAuth(); const [draft,setDraft] = useState(''); const chat = usePhoneChat(user?.role === 'admin' ? user.id : null);
  if (user?.role !== 'admin') return <p role="alert">Admin access required.</p>;
  async function submit(event) { event.preventDefault(); if (await chat.send(draft)) setDraft(''); }
  return <div className="mx-auto max-w-3xl space-y-6"><div><p className="agency-eyebrow mb-2">PHONE · WHATSAPP · WINDOWS</p><h1 className="mb-2 text-2xl">Phone & WhatsApp</h1><p className="mb-0 text-sm text-muted-foreground">Connect your phone to the agency assistant and open your conversations from Windows.</p></div><PhoneConnectionLinks/><section className="space-y-4"><h2 className="mb-0 text-xl">Phone assistant conversations</h2><div className="flex flex-wrap items-end gap-3"><label className="min-w-0 flex-1 text-xs">Saved conversation<select value={chat.current?.id || ''} disabled={chat.busy || chat.loading} onChange={event => event.target.value ? chat.select(event.target.value) : chat.newChat()} className="agency-input"><option value="">New conversation</option>{chat.conversations.map(conversation => <option key={conversation.id} value={conversation.id}>{conversation.metadata?.name || `Conversation · ${new Date(conversation.created_date).toLocaleDateString()}`}</option>)}</select></label><button type="button" disabled={chat.busy || chat.loading} onClick={chat.newChat} className="rounded-lg border border-border px-4 py-3 text-xs disabled:opacity-50">New chat</button><button type="button" disabled={chat.busy || chat.loading} onClick={chat.refresh} className="rounded-lg border border-border px-4 py-3 text-xs disabled:opacity-50">Refresh</button></div>{chat.loading && <p role="status" className="text-xs">Loading saved conversations…</p>}{chat.error && <p role="alert" className="text-sm text-destructive">{chat.error}</p>}<PhoneAgentMessages messages={chat.current?.messages || []} busy={chat.busy}/><form onSubmit={submit} className="flex flex-col gap-3"><label className="text-xs">Message<textarea value={draft} onChange={event => setDraft(event.target.value)} rows={3} disabled={chat.busy || chat.loading} placeholder="Ask for a plan or draft. Computer commands are not executed." className="agency-input"/></label><button type="submit" disabled={chat.busy || chat.loading || !draft.trim()} className="agency-button self-end">{chat.busy ? 'Sending…' : 'Send'}</button></form><p className="mb-0 text-xs text-muted-foreground">These assistant conversations are saved to your signed-in account rather than this browser. Select the same conversation on another device; Refresh loads newly created threads. WhatsApp uses its own channel thread—select it if it appears here. Personal ChatGPT conversations are not imported.</p></section></div>;
}