import { useState } from 'react';
import { KeyRound, FileLock2, UserRound, Eye, EyeOff, Pencil, Trash2, Copy } from 'lucide-react';
const names = { login: 'Account login', api_key: 'API key / token', note: 'Secure note' };
const icons = { login: UserRound, api_key: KeyRound, note: FileLock2 };
export default function CredentialItem({ item, onRead, onEdit, onDelete }) {
  const [revealed, setRevealed] = useState(null), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState('');
  const Icon = icons[item.category];
  async function run(operation) { setBusy(true); setError(''); setMessage(''); try { await operation(); } catch (failure) { setError(failure.message); } finally { setBusy(false); } }
  const reveal = () => run(async () => setRevealed(revealed ? null : await onRead(item.id)));
  const copy = () => run(async () => { const values = revealed || await onRead(item.id); await navigator.clipboard.writeText(item.category === 'note' ? values.notes : values.secret); setMessage('Copied to clipboard.'); });
  return <article className="min-w-0 rounded-xl border border-border bg-card p-5"><div className="mb-4 flex items-start justify-between gap-3"><div className="flex min-w-0 items-start gap-3"><Icon size={21} className="mt-1 shrink-0 text-primary" aria-hidden="true"/><div className="min-w-0"><h3 className="mb-1 break-words text-base">{item.title}</h3><p className="mb-0 break-words text-xs text-muted-foreground">{names[item.category]}{item.provider && ` · ${item.provider}`}</p></div></div><div className="flex shrink-0"><button type="button" disabled={busy} onClick={() => run(() => onEdit(item))} aria-label={`Edit ${item.title}`} className="inline-flex h-11 w-11 items-center justify-center rounded-lg text-primary hover:bg-muted"><Pencil size={17}/></button><button type="button" disabled={busy} onClick={() => { if (window.confirm(`Delete “${item.title}” from your vault?`)) run(() => onDelete(item.id)); }} aria-label={`Delete ${item.title}`} className="inline-flex h-11 w-11 items-center justify-center rounded-lg text-destructive hover:bg-muted"><Trash2 size={17}/></button></div></div>{revealed ? <div className="space-y-3 rounded-lg bg-muted p-4 text-sm">{revealed.username && <p className="mb-0 break-all"><span className="block text-xs text-muted-foreground">Username / label</span>{revealed.username}</p>}{item.category !== 'note' && <p className="mb-0 whitespace-pre-wrap break-all font-mono">{revealed.secret}</p>}{revealed.notes && <p className="mb-0 whitespace-pre-wrap break-words">{revealed.notes}</p>}{revealed.url?.startsWith('https://') && <a href={revealed.url} target="_blank" rel="noopener noreferrer" className="inline-flex min-h-11 items-center break-all text-primary underline">Open account dashboard</a>}</div> : <div className="rounded-lg bg-muted px-4 py-3 font-mono text-sm text-muted-foreground">{item.category === 'note' ? 'Note contents encrypted' : '••••••••••••••••'}</div>}<div className="mt-3 flex flex-wrap gap-4"><button type="button" disabled={busy} onClick={reveal} aria-pressed={Boolean(revealed)} className="inline-flex min-h-11 items-center gap-2 text-sm text-primary">{revealed ? <EyeOff size={16}/> : <Eye size={16}/>}{revealed ? 'Hide' : 'Reveal'}</button><button type="button" disabled={busy} onClick={copy} className="inline-flex min-h-11 items-center gap-2 text-sm text-primary"><Copy size={16}/>Copy {item.category === 'note' ? 'note' : item.category === 'login' ? 'password' : 'key'}</button></div>{busy && <p role="status" className="mb-0 text-xs text-muted-foreground">Working…</p>}{message && <p role="status" className="mb-0 text-xs text-muted-foreground">{message}</p>}{error && <p role="alert" className="mb-0 text-sm text-destructive">{error}</p>}<p className="mb-0 mt-3 text-xs text-muted-foreground">Updated {new Date(item.updated_at).toLocaleDateString()}</p></article>;
}