import { useEffect, useState } from 'react';
import { readVaultPage, deleteVaultEntry } from '@/components/portal/vault/secureVaultStore';
import CredentialItem from '@/components/portal/vault/CredentialItem';
export default function CredentialList({ vault, refresh, onEdit, onAdd }) {
  const [search, setSearch] = useState(''), [category, setCategory] = useState(''), [offset, setOffset] = useState(0), [items, setItems] = useState([]), [more, setMore] = useState(false), [loading, setLoading] = useState(true), [error, setError] = useState(''), [revision, setRevision] = useState(0);
  useEffect(() => {
    let active = true; setLoading(true); setError('');
    const timer = setTimeout(() => { readVaultPage(vault.owner, search, category, offset).then(page => { if (active) { setItems(page.slice(0, 50)); setMore(page.length > 50); } }).catch(failure => { if (active) setError(failure.message); }).finally(() => { if (active) setLoading(false); }); }, 250);
    return () => { active = false; clearTimeout(timer); };
  }, [vault.owner, search, category, offset, refresh, revision]);
  async function remove(id) { await deleteVaultEntry(vault.owner, id); if (items.length === 1 && offset) setOffset(Math.max(0, offset - 50)); setRevision(value => value + 1); }
  return <section className="space-y-5"><div className="grid gap-3 sm:grid-cols-[1fr_200px]"><label className="text-sm">Search item names<input type="search" value={search} onChange={event => { setSearch(event.target.value); setOffset(0); }} placeholder="Search saved credentials…" className="agency-input"/></label><label className="text-sm">Item type<select value={category} onChange={event => { setCategory(event.target.value); setOffset(0); }} className="agency-input"><option value="">All items</option><option value="login">Account logins</option><option value="api_key">API keys & tokens</option><option value="note">Secure notes</option></select></label></div>{error && <p role="alert" className="text-sm text-destructive">{error} <button type="button" onClick={() => setRevision(value => value + 1)} className="text-primary underline">Retry</button></p>}{loading ? <p role="status" className="py-8 text-center text-sm">Loading vault items…</p> : !error && !items.length ? <div className="rounded-xl border border-dashed border-border bg-card px-6 py-12 text-center"><h3 className="mb-2 text-lg">{search || category ? 'No matching items' : 'Your encrypted vault is ready'}</h3><p className="mb-5 text-sm text-muted-foreground">{search || category ? 'Try another name or item type.' : 'Add your first password, API key or secure note.'}</p><button type="button" onClick={onAdd} className="agency-button">Add vault item</button></div> : <div className="grid gap-4 lg:grid-cols-2">{items.map(item => <CredentialItem key={`${item.id}:${item.updated_at}`} item={item} onRead={vault.read} onEdit={onEdit} onDelete={remove}/>)}</div>}{!loading && (offset > 0 || more) && <div className="flex justify-between gap-4"><button type="button" disabled={!offset} onClick={() => setOffset(value => Math.max(0, value - 50))} className="min-h-11 rounded-lg border border-border px-4 text-sm disabled:opacity-50">Previous</button><button type="button" disabled={!more} onClick={() => setOffset(value => value + 50)} className="min-h-11 rounded-lg border border-border px-4 text-sm disabled:opacity-50">Next</button></div>}</section>;
}