import { useEffect, useState } from 'react';
import { base44 } from '@/api/base44Client';
import VaultBackupPreview from '@/components/portal/vault/VaultBackupPreview';
export default function VaultBackups() {
  const [files,setFiles] = useState([]), [busy,setBusy] = useState('loading'), [error,setError] = useState(''), [snapshot,setSnapshot] = useState(null);
  async function request(action, extra = {}) { const { data } = await base44.functions.invoke('vaultBackup', { action, ...extra }); return data; }
  async function load() { setFiles((await request('list')).files); }
  async function run(label, action) { setBusy(label); setError(''); try { await action(); } catch (failure) { setError(failure.response?.data?.error || failure.message || 'Backup request failed.'); } finally { setBusy(''); } }
  useEffect(() => { run('loading', load); }, []);
  return <section className="space-y-4"><h2 className="mb-0 text-xl">Encrypted vault backups</h2><p className="mb-0 text-sm text-muted-foreground">Daily backup scheduled for 02:00 UTC, independent of an open browser. Saved files below are evidence of completed backups; a configured schedule alone does not verify that an automated run succeeded.</p><p className="mb-0 text-xs text-muted-foreground">AES-256-GCM encryption happens before upload to a dedicated, owner-only agency Drive folder. The protected key stays on the server; preview access requires your admin account. Drive’s owner can still see or delete the encrypted files.</p><p className="mb-0 text-xs text-muted-foreground">Only your vault account references and stored access-key records are backed up. Provider secrets, Google login tokens, and generator outputs not saved in the vault are excluded. Keep the encryption key protected—losing it makes these backups unreadable.</p><div className="flex flex-wrap gap-3"><button type="button" disabled={!!busy} onClick={() => run('creating', async () => { await request('create'); await load(); })} className="agency-button">{busy === 'creating' ? 'Backing up…' : 'Back up now'}</button><button type="button" disabled={!!busy} onClick={() => run('loading', load)} className="rounded-lg border border-border px-4 py-2 text-xs disabled:opacity-50">Refresh backups</button></div>{busy === 'loading' && <p role="status" className="text-sm">Loading backups…</p>}{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<p className="mb-0 text-xs text-muted-foreground">Latest 30 backups for your admin account</p>{files.length ? <ul className="divide-y divide-border">{files.map(file => <li key={file.id} className="flex flex-wrap items-center justify-between gap-3 py-3"><span className="min-w-0 break-all text-sm">{file.name}<time className="block text-xs text-muted-foreground">{new Date(file.createdTime).toLocaleString()}</time></span><button type="button" disabled={!!busy} onClick={() => run('preview', async () => { setSnapshot(null); setSnapshot((await request('preview', { fileId: file.id })).snapshot); })} className="rounded-lg border border-border px-3 py-2 text-xs disabled:opacity-50">View securely</button></li>)}</ul> : !busy && !error && <p className="text-sm">No saved backups yet. Create the first backup now.</p>}{busy === 'preview' && <p role="status" className="text-sm">Decrypting backup securely…</p>}<VaultBackupPreview snapshot={snapshot} onClose={() => setSnapshot(null)}/></section>;
}