// Migrated provisionSite — runs on Railway, reads/writes Supabase.
// Auth bridge validates the Base44 token; admin-only.
// GitHub token comes from the Base44 connector (fetched via the auth bridge
// function below) OR a GITHUB_TOKEN env var on Railway. Vercel uses VERCEL_API_TOKEN.
import { Router } from 'express';
import { supabase, tableName } from '../lib/supabase.js';
import { requireAdmin } from '../lib/auth.js';

export const provisionSiteRouter = Router();

function slugify(name) {
  return name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '').slice(0, 63);
}

async function providerError(res, provider) {
  const data = await res.json().catch(() => ({}));
  throw new Error(`${provider}: ${data.error?.message || data.message || data.error || `request failed (${res.status})`}`);
}

// ── GitHub: create repo ──
async function createGitHubRepo(accessToken, slug, description) {
  const res = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: { Authorization: `Bearer ${accessToken}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ name: slug, description, private: true, auto_init: true }),
  });
  if (!res.ok) await providerError(res, 'GitHub');
  return await res.json();
}

// ── GitHub: push files via Git Data API ──
async function pushFilesToGitHub(accessToken, owner, repo, branch, files) {
  const headers = { Authorization: `Bearer ${accessToken}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' };
  const refRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`, { headers });
  if (!refRes.ok) await providerError(refRes, 'GitHub');
  const ref = await refRes.json();
  const commitSha = ref.object.sha;
  const commitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits/${commitSha}`, { headers });
  if (!commitRes.ok) await providerError(commitRes, 'GitHub');
  const commit = await commitRes.json();
  const treeEntries = Object.entries(files).map(([path, content]) => ({ path, mode: '100644', type: 'blob', content }));
  const treeRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/trees`, { method: 'POST', headers, body: JSON.stringify({ base_tree: commit.tree.sha, tree: treeEntries }) });
  if (!treeRes.ok) await providerError(treeRes, 'GitHub');
  const tree = await treeRes.json();
  const newCommitRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/commits`, { method: 'POST', headers, body: JSON.stringify({ message: 'Initial site generated by Strategic Minds AI', tree: tree.sha, parents: [commitSha] }) });
  if (!newCommitRes.ok) await providerError(newCommitRes, 'GitHub');
  const newCommit = await newCommitRes.json();
  const updateRefRes = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs/heads/${branch}`, { method: 'PATCH', headers, body: JSON.stringify({ sha: newCommit.sha }) });
  if (!updateRefRes.ok) await providerError(updateRefRes, 'GitHub');
  return { commit_sha: newCommit.sha, file_count: Object.keys(files).length };
}

async function createVercelProject(slug, githubRepo) {
  const token = process.env.VERCEL_API_TOKEN;
  if (!token) throw new Error('VERCEL_API_TOKEN not configured');
  const res = await fetch('https://api.vercel.com/v11/projects', { method: 'POST', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify({ name: slug, gitRepository: { type: 'github', repo: githubRepo }, framework: null }) });
  if (!res.ok) await providerError(res, 'Vercel');
  return await res.json();
}

async function getVercelDeployments(projectId) {
  const token = process.env.VERCEL_API_TOKEN;
  const res = await fetch(`https://api.vercel.com/v6/deployments?projectId=${projectId}&limit=1`, { headers: { Authorization: `Bearer ${token}` } });
  if (!res.ok) return [];
  const data = await res.json();
  return data.deployments || [];
}

function generateStaticFiles(html, name) {
  const slug = slugify(name);
  return {
    'index.html': html,
    'vercel.json': JSON.stringify({ name: slug, public: true, cleanUrls: true }, null, 2),
    'README.md': `# ${name}\n\nGenerated by Strategic Minds AI.\n`,
    '.gitignore': '.vercel\nnode_modules\n',
  };
}

function generateViteFiles(buildSpec, projectName) {
  const slug = slugify(projectName);
  const tokens = buildSpec?.tokens?.primitive || {};
  const primaryColor = tokens['color.primary.500'] || '#0066ff';
  const indexHtml = `<!DOCTYPE html>\n<html lang="en">\n<head>\n<meta charset="UTF-8" />\n<meta name="viewport" content="width=device-width, initial-scale=1.0" />\n<title>${projectName}</title>\n</head>\n<body>\n<div id="root"></div>\n<script type="module" src="/src/main.jsx"></script>\n</body>\n</html>`;
  const packageJson = JSON.stringify({ name: slug, private: true, version: '0.0.1', type: 'module', scripts: { dev: 'vite', build: 'vite build', preview: 'vite preview' }, dependencies: { react: '^18.2.0', 'react-dom': '^18.2.0' }, devDependencies: { '@vitejs/plugin-react': '^4.2.0', vite: '^5.0.0', tailwindcss: '^3.4.0', postcss: '^8.4.0', autoprefixer: '^10.4.0' } }, null, 2);
  const viteConfig = `import { defineConfig } from 'vite'\nimport react from '@vitejs/plugin-react'\n\nexport default defineConfig({\n  plugins: [react()],\n})`;
  const tailwindConfig = `/** @type {import('tailwindcss').Config} */\nexport default {\n  content: ['./index.html', './src/**/*.{js,jsx}'],\n  theme: { extend: { colors: { primary: '${primaryColor}' } },\n  },\n  plugins: [],\n}`;
  const postcssConfig = `export default {\n  plugins: { tailwindcss: {}, autoprefixer: {} },\n}`;
  const mainJsx = `import React from 'react'\nimport ReactDOM from 'react-dom/client'\nimport App from './App.jsx'\nimport './index.css'\n\nReactDOM.createRoot(document.getElementById('root')).render(\n  <React.StrictMode>\n    <App />\n  </React.StrictMode>,\n)`;
  const screens = buildSpec?.screens || [];
  const navLinks = screens.map((s) => `<a href="${s.route}" className="hover:text-primary">${s.name}</a>`).join('\n            ');
  const featureCards = screens.slice(0, 3).map((s, i) => `          <div key={${i}} className="rounded-xl border border-gray-200 bg-white p-6">\n            <h2 className="text-xl font-semibold">${s.name}</h2>\n            <p className="mt-2 text-sm text-gray-600">${(s.content || []).join(' · ') || 'Content placeholder'}</p>\n          </div>`).join('\n');
  const appJsx = `import React from 'react'\n\nexport default function App() {\n  return (\n    <div className="min-h-screen bg-gray-50 text-gray-900">\n      <header className="border-b border-gray-200 bg-white px-6 py-4">\n        <nav className="mx-auto flex max-w-5xl items-center justify-between">\n          <span className="text-lg font-bold text-primary">${projectName}</span>\n          <div className="flex gap-6 text-sm text-gray-600">\n            ${navLinks}\n          </div>\n        </nav>\n      </header>\n      <main className="mx-auto max-w-5xl px-6 py-12">\n        <section className="mb-16 text-center">\n          <h1 className="text-4xl font-bold text-gray-900">${projectName}</h1>\n          <p className="mt-4 text-lg text-gray-600">Generated by Strategic Minds AI</p>\n          <a href="/contact" className="mt-8 inline-block rounded-lg bg-primary px-6 py-3 text-white hover:opacity-90">Get Started</a>\n        </section>\n        <section className="grid grid-cols-1 gap-8 md:grid-cols-3">\n${featureCards}\n        </section>\n      </main>\n      <footer className="border-t border-gray-200 bg-white px-6 py-8 text-center text-sm text-gray-500">\n        <p>&copy; ${new Date().getFullYear()} ${projectName}. All rights reserved.</p>\n      </footer>\n    </div>\n  )\n}`;
  const cssVars = Object.entries(tokens).filter(([k]) => k.startsWith('color.')).slice(0, 10).map(([k, v]) => `  --${k.replace(/\./g, '-')}: ${v};`).join('\n');
  const indexCss = `@tailwind base;\n@tailwind components;\n@tailwind utilities;\n\n:root {\n${cssVars}\n}`;
  return {
    'index.html': indexHtml, 'package.json': packageJson, 'vite.config.js': viteConfig, 'tailwind.config.js': tailwindConfig, 'postcss.config.js': postcssConfig,
    'src/main.jsx': mainJsx, 'src/App.jsx': appJsx, 'src/index.css': indexCss,
    'README.md': `# ${projectName}\n\nGenerated by Strategic Minds AI — UFF v${buildSpec?.registry_version || '2.0.0'}.\n`,
    '.gitignore': 'node_modules\ndist\n.env\n',
  };
}

// Resolve a GitHub token: prefer GITHUB_TOKEN env on Railway, else fetch
// from the Base44 connector via the auth bridge function.
async function getGitHubToken(req) {
  if (process.env.GITHUB_TOKEN) return process.env.GITHUB_TOKEN;
  const auth = req.headers.get('authorization') || req.headers.authorization;
  const res = await fetch(`${process.env.BASE44_APP_URL || 'https://strategic-ai-consulting.base44.app'}/functions/authContext`, {
    headers: { Authorization: auth, 'x-connector': 'github' },
  });
  if (!res.ok) throw new Error('Could not resolve GitHub connector token');
  const data = await res.json();
  return data.connectorToken;
}

// ── Routes ──
provisionSiteRouter.post('/', async (req, res) => {
  try {
    const user = await requireAdmin(req, res);
    if (!user) return;
    const body = req.body || {};
    const action = body.action || 'list';

    if (action === 'provision') {
      const { project_name, template_id, build_spec, custom_html, needs_backend, supabase_region } = body;
      if (!project_name) return res.status(400).json({ error: 'project_name required' });
      const slug = slugify(project_name);

      const { data: site, error: ce } = await supabase.from(tableName('ProvisionedSite')).insert({
        project_name, slug, template_id: template_id || '', build_spec_id: build_spec?.project_id || '',
        site_type: custom_html || template_id ? 'static_html' : 'vite_react', needs_backend: !!needs_backend,
        supabase_region: supabase_region || 'us-east-1', supabase_plan: 'free', status: 'pending',
        progress_step: 'Starting provisioning pipeline', provisioned_at: new Date().toISOString(), created_by: user.id,
      }).select().single();
      if (ce) throw new Error(ce.message);

      try {
        let files;
        if (custom_html) {
          files = generateStaticFiles(custom_html, project_name);
          await supabase.from(tableName('ProvisionedSite')).update({ progress_step: 'Using custom HTML' }).eq('id', site.id);
        } else if (template_id) {
          const { data: template } = await supabase.from(tableName('TemplateAsset')).select('*').eq('id', template_id).single();
          if (!template) throw new Error('Template not found');
          files = generateStaticFiles(template.raw_content || '', project_name);
          await supabase.from(tableName('ProvisionedSite')).update({ progress_step: 'Using ingested template' }).eq('id', site.id);
        } else if (build_spec) {
          files = generateViteFiles(build_spec, project_name);
          await supabase.from(tableName('ProvisionedSite')).update({ progress_step: 'Using UFF BuildSpec', site_type: 'vite_react' }).eq('id', site.id);
        } else {
          throw new Error('Provide template_id, build_spec, or custom_html');
        }

        await supabase.from(tableName('ProvisionedSite')).update({ progress_step: 'Creating GitHub repository' }).eq('id', site.id);
        const ghToken = await getGitHubToken(req);
        const repo = await createGitHubRepo(ghToken, slug, `Site generated by Strategic Minds AI — ${project_name}`);
        const owner = repo.owner.login;
        const repoFullName = repo.full_name;
        const branch = repo.default_branch || 'main';
        await supabase.from(tableName('ProvisionedSite')).update({ github_repo: repoFullName, github_url: repo.html_url, github_default_branch: branch, status: 'github_created', progress_step: 'Pushing site files to GitHub' }).eq('id', site.id);

        await pushFilesToGitHub(ghToken, owner, repo.name, branch, files);
        await supabase.from(tableName('ProvisionedSite')).update({ status: 'files_pushed', progress_step: 'Creating Vercel project' }).eq('id', site.id);

        const vercelProject = await createVercelProject(slug, repoFullName);
        await supabase.from(tableName('ProvisionedSite')).update({ vercel_project_id: vercelProject.id, vercel_url: `https://vercel.com/${vercelProject.id}`, status: 'vercel_connected', progress_step: needs_backend ? 'Creating Supabase project' : 'Finalizing deployment' }).eq('id', site.id);

        if (needs_backend) {
          // Supabase project creation would use the Supabase connector token.
          // For now, mark as skipped — can be wired via the auth bridge connector token.
          await supabase.from(tableName('ProvisionedSite')).update({ progress_step: 'Supabase project creation deferred (wire connector token)' }).eq('id', site.id);
        }

        await new Promise((r) => setTimeout(r, 3000));
        let deploymentUrl = '';
        try {
          const deployments = await getVercelDeployments(vercelProject.id);
          if (deployments.length > 0 && deployments[0].url) deploymentUrl = `https://${deployments[0].url}`;
        } catch {}

        await supabase.from(tableName('ProvisionedSite')).update({ status: 'deployed', progress_step: 'Provisioning complete', vercel_deployment_url: deploymentUrl, deployment_url: deploymentUrl || `https://${slug}.vercel.app`, deployed_at: new Date().toISOString() }).eq('id', site.id);

        const { data: final } = await supabase.from(tableName('ProvisionedSite')).select('*').eq('id', site.id).single();
        return res.json({ ok: true, site: final });
      } catch (err) {
        await supabase.from(tableName('ProvisionedSite')).update({ status: 'failed', error: err.message, progress_step: 'Provisioning failed' }).eq('id', site.id);
        return res.status(500).json({ error: err.message, site_id: site.id });
      }
    }

    if (action === 'list') {
      const { data, error } = await supabase.from(tableName('ProvisionedSite')).select('*').order('created_at', { ascending: false }).limit(100);
      if (error) throw new Error(error.message);
      return res.json({ sites: data || [] });
    }

    if (action === 'get') {
      const { site_id } = body;
      if (!site_id) return res.status(400).json({ error: 'site_id required' });
      const { data, error } = await supabase.from(tableName('ProvisionedSite')).select('*').eq('id', site_id).single();
      if (error) return res.status(404).json({ error: 'Site not found' });
      return res.json({ site: data });
    }

    if (action === 'delete') {
      const { site_id } = body;
      if (!site_id) return res.status(400).json({ error: 'site_id required' });
      await supabase.from(tableName('ProvisionedSite')).delete().eq('id', site_id);
      return res.json({ ok: true, deleted: site_id });
    }

    if (action === 'refresh_deployment') {
      const { site_id } = body;
      if (!site_id) return res.status(400).json({ error: 'site_id required' });
      const { data: site } = await supabase.from(tableName('ProvisionedSite')).select('*').eq('id', site_id).single();
      if (!site || !site.vercel_project_id) return res.status(404).json({ error: 'Site or Vercel project not found' });
      const deployments = await getVercelDeployments(site.vercel_project_id);
      let deploymentUrl = '';
      if (deployments.length > 0 && deployments[0].url) deploymentUrl = `https://${deployments[0].url}`;
      if (deploymentUrl) {
        await supabase.from(tableName('ProvisionedSite')).update({ vercel_deployment_url: deploymentUrl, deployment_url: deploymentUrl, status: 'deployed' }).eq('id', site_id);
      }
      return res.json({ ok: true, deployment_url: deploymentUrl, deployments: deployments.length });
    }

    return res.status(400).json({ error: `Unknown action: ${action}` });
  } catch (error) {
    console.error('Provision site error:', error.message);
    return res.status(500).json({ error: error.message });
  }
});