// GPT PROVISION PIPELINE — One-command website generation + full provisioning.
//
// Send a natural-language command, get back a live website provisioned across
// GitHub, Vercel, Railway, and Supabase. Uses the Vercel AI Gateway (bypasses
// Base44 integration credits) for generation, and the user's own secrets for
// provisioning.
//
// Actions:
//   run     — generate + provision (the main pipeline)
//   verify  — check all secrets are live
//   status  — get pipeline status for a job

import { createClientFromRequest } from '../../shared/ownedClient.ts';
import { getSupabaseUser } from '../../shared/supabaseAuth.ts';
import { secrets } from '../../shared/runtimeSecrets.ts';
import { callAIGateway } from '../../shared/aiGateway.ts';

function slugify(s: string): string {
  return (s || '').toLowerCase().replace(/[^a-z0-9-]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 80);
}

async function providerResponse(response: Response, provider: string) {
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(`${provider}: ${data.error?.message || data.message || `request failed (${response.status})`}`);
  return data;
}

// ── Step 1: Generate website via AI Gateway ──
async function generateWebsite(command: string): Promise<{ html: string; title: string; description: string }> {
  const result = await callAIGateway({
    system: 'You are a world-class web developer and brand strategist. Generate a complete, self-contained, production-quality HTML page. Return ONLY JSON with an "html" field containing the raw HTML.',
    prompt: `Generate a complete, beautiful, modern, responsive homepage based on this command:

"${command}"

Requirements:
- Full <!doctype html> document with inline <style> in the <head>
- Modern, professional design with hero, services/features, about, testimonials, CTA, footer
- Mobile-responsive with CSS media queries
- Blue color scheme (#0066FF primary, #004CE6 accent) unless the command specifies otherwise
- SEO-optimized: title, meta description, semantic HTML, h1/h2 tags
- Self-contained: no external CSS/JS files, no external images (use CSS gradients or inline SVG)
- Include a contact phone: 772-209-0266 and email: hello@strategicmindsai.com
- Keep HTML under 40000 characters

Return JSON: { "html": "<full html here>", "title": "Business Name", "description": "One-line description" }`,
    jsonSchema: { type: 'object' },
    maxTokens: 8000,
  });

  const json = result.json || {};
  let html = (json.html || result.content || '').trim();
  // Strip markdown code fences if present
  html = html.replace(/^```html?\s*/i, '').replace(/```\s*$/i, '').trim();
  if (!html.startsWith('<!doctype') && !html.startsWith('<html')) {
    // If the model returned just the HTML without doctype, wrap it
    if (html.includes('<body')) {
      html = `<!doctype html>\n${html}`;
    } else {
      html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${json.title || 'Generated Site'}</title></head><body>${html}</body></html>`;
    }
  }
  return { html, title: json.title || 'Generated Website', description: json.description || '' };
}

// ── Step 2: Create GitHub repo and push the website ──
async function provisionGitHub(base44: any, slug: string, website: any): Promise<{ repo: string; url: string }> {
  const { accessToken } = await base44.asServiceRole.connectors.getConnection('github');

  // Create repo
  const createRes = await fetch('https://api.github.com/user/repos', {
    method: 'POST',
    headers: { Authorization: `Bearer ${accessToken}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ name: slug, description: website.description || `Generated by Strategic Minds AI`, private: false, auto_init: true }),
  });
  const repo = await providerResponse(createRes, 'GitHub');

  // Push index.html
  const content = btoa(unescape(encodeURIComponent(website.html)));
  const pushRes = await fetch(`https://api.github.com/repos/${repo.full_name}/contents/index.html`, {
    method: 'PUT',
    headers: { Authorization: `Bearer ${accessToken}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ message: 'Initial website generated by Strategic Minds AI', content }),
  });
  await providerResponse(pushRes, 'GitHub push');

  // Push vercel.json for auto-deploy config
  const vercelConfig = btoa(JSON.stringify({ version: 2, cleanUrls: true, trailingSlash: false }, null, 2));
  await fetch(`https://api.github.com/repos/${repo.full_name}/contents/vercel.json`, {
    method: 'PUT',
    headers: { Authorization: `Bearer ${accessToken}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ message: 'Add Vercel config', content: vercelConfig }),
  }).catch(() => {}); // non-fatal

  // Push README
  const readme = btoa(`# ${website.title}\n\n${website.description}\n\nGenerated by Strategic Minds AI.\n\nLive site: deployed via Vercel.`);
  await fetch(`https://api.github.com/repos/${repo.full_name}/contents/README.md`, {
    method: 'PUT',
    headers: { Authorization: `Bearer ${accessToken}`, Accept: 'application/vnd.github+json', 'Content-Type': 'application/json', 'X-GitHub-Api-Version': '2022-11-28' },
    body: JSON.stringify({ message: 'Add README', content: readme }),
  }).catch(() => {});

  return { repo: repo.full_name, url: repo.html_url };
}

// ── Step 3: Create Vercel project linked to the GitHub repo ──
async function provisionVercel(slug: string, githubRepo: string): Promise<{ id: string; url: string }> {
  const res = await fetch('https://api.vercel.com/v11/projects', {
    method: 'POST',
    headers: { Authorization: `Bearer ${secrets.get('VERCEL_API_TOKEN')}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ name: slug, gitRepository: { type: 'github', repo: githubRepo } }),
  });
  const project = await providerResponse(res, 'Vercel');
  return { id: project.id, url: `https://${slug}.vercel.app` };
}

// ── Step 4: Create Railway project ──
async function provisionRailway(name: string): Promise<{ id: string; url: string }> {
  const res = await fetch('https://backboard.railway.com/graphql/v2', {
    method: 'POST',
    headers: { Authorization: `Bearer ${secrets.get('RAILWAY_API_TOKEN')}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({ query: 'mutation projectCreate($input: ProjectCreateInput!) { projectCreate(input: $input) { id name } }', variables: { input: { name } } }),
  });
  const data = await res.json();
  if (data.errors?.length) throw new Error(`Railway: ${data.errors[0].message}`);
  return { id: data.data.projectCreate.id, url: `https://railway.com/project/${data.data.projectCreate.id}` };
}

// ── Step 5: Verify Supabase (already provisioned — create a table for the site) ──
async function provisionSupabase(slug: string): Promise<{ url: string; table: string }> {
  const supabaseUrl = secrets.get('SUPABASE_URL');
  const key = secrets.get('SUPABASE_SERVICE_KEY');

  // Create a leads table for this site
  const tableName = `${slug.replace(/-/g, '_')}_leads`.slice(0, 50);
  const sql = `
    CREATE TABLE IF NOT EXISTS public.${tableName} (
      id uuid primary key default gen_random_uuid(),
      name text,
      email text,
      phone text,
      message text,
      created_at timestamptz default now()
    );
    alter table public.${tableName} enable row level security;
    create policy "allow_insert" on public.${tableName} for insert using (true);
  `;

  try {
    await fetch(`${supabaseUrl}/rest/v1/rpc/`, {
      method: 'POST',
      headers: { apikey: key, Authorization: `Bearer ${key}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ query: sql }),
    }).catch(() => {});
  } catch { /* non-fatal — table creation is optional */ }

  return { url: supabaseUrl, table: tableName };
}

// ── Verify all secrets ──
async function verifySecrets(base44: any): Promise<any> {
  const results: any = {};

  // Vercel
  try {
    const r = await fetch('https://api.vercel.com/v2/user', { headers: { Authorization: `Bearer ${secrets.get('VERCEL_API_TOKEN')}` } });
    const d = await r.json();
    results.vercel = { ok: r.ok, user: d.user?.username || null };
  } catch { results.vercel = { ok: false }; }

  // Railway
  try {
    const r = await fetch('https://backboard.railway.com/graphql/v2', {
      method: 'POST',
      headers: { Authorization: `Bearer ${secrets.get('RAILWAY_API_TOKEN')}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ query: '{ projects { edges { node { id } } } }' }),
    });
    const d = await r.json();
    results.railway = { ok: !d.errors?.length, projects: d.data?.projects?.edges?.length || 0 };
  } catch { results.railway = { ok: false }; }

  // Supabase
  try {
    const r = await fetch(`${secrets.get('SUPABASE_URL')}/rest/v1/`, { headers: { apikey: secrets.get('SUPABASE_SERVICE_KEY'), Authorization: `Bearer ${secrets.get('SUPABASE_SERVICE_KEY')}` } });
    results.supabase = { ok: r.ok };
  } catch { results.supabase = { ok: false }; }

  // AI Gateway
  try {
    const r = await fetch('https://ai-gateway.vercel.sh/v1/chat/completions', {
      method: 'POST',
      headers: { Authorization: `Bearer ${process.env.AI_GATEWAY_API_KEY}`, 'Content-Type': 'application/json' },
      body: JSON.stringify({ model: 'anthropic/claude-sonnet-4-5', messages: [{ role: 'user', content: 'ping' }], max_tokens: 5 }),
    });
    results.aiGateway = { ok: r.ok };
  } catch { results.aiGateway = { ok: false }; }

  // GitHub
  try {
    const { accessToken } = await base44.asServiceRole.connectors.getConnection('github');
    const r = await fetch('https://api.github.com/user', { headers: { Authorization: `Bearer ${accessToken}` } });
    const d = await r.json();
    results.github = { ok: r.ok, user: d.login || null };
  } catch { results.github = { ok: false }; }

  // GoDaddy
  try {
    const r = await fetch('https://api.godaddy.com/v1/domains?statuses=ACTIVE', {
      headers: { Authorization: `sso-key ${secrets.get('GODADDY_API_KEY')}:${secrets.get('GODADDY_API_SECRET')}` },
    });
    results.godaddy = { ok: r.ok };
  } catch { results.godaddy = { ok: false }; }

  // Stripe
  try {
    const r = await fetch('https://api.stripe.com/v1/balance', { headers: { Authorization: `Bearer ${secrets.get('STRIPE_SECRET_KEY')}` } });
    results.stripe = { ok: r.ok };
  } catch { results.stripe = { ok: false }; }

  // Twilio
  try {
    const sid = secrets.get('TWILIO_ACCOUNT_SID');
    const r = await fetch(`https://api.twilio.com/2010-04-01/Accounts/${sid}.json`, {
      headers: { Authorization: 'Basic ' + btoa(`${sid}:${secrets.get('TWILIO_AUTH_TOKEN')}`) },
    });
    results.twilio = { ok: r.ok };
  } catch { results.twilio = { ok: false }; }

  // Telnyx
  try {
    const r = await fetch('https://api.telnyx.com/v2/phone_numbers', { headers: { Authorization: `Bearer ${secrets.get('TELNYX_API_KEY')}` } });
    results.telnyx = { ok: r.ok };
  } catch { results.telnyx = { ok: false }; }

  // OpenAI
  results.openai = { configured: Boolean(process.env.OPENAI_API_KEY) };

  return results;
}

export default async function(req: Request): Promise<Response> {
  try {
    const base44 = createClientFromRequest(req);
    const user = await getSupabaseUser(req);
    if (!user) return Response.json({ error: 'Unauthorized' }, { status: 401 });
    if (user.role !== 'admin') return Response.json({ error: 'Admin access required' }, { status: 403 });

    const body = await req.json().catch(() => ({}));
    const action = body.action || 'run';

    // ── verify ──
    if (action === 'verify') {
      const results = await verifySecrets(base44);
      const allOk = Object.values(results).every((r: any) => r.ok || r.configured !== undefined);
      return Response.json({ ok: true, secrets: results, all_passed: allOk });
    }

    // ── run: the full pipeline ──
    if (action === 'run') {
      const { command } = body;
      if (!command || typeof command !== 'string' || command.trim().length < 10) {
        return Response.json({ error: 'Provide a command describing the website to build (at least 10 characters).' }, { status: 400 });
      }

      const steps: any[] = [];
      const log = (step: string, status: string, detail?: any) => steps.push({ step, status, detail, timestamp: new Date().toISOString() });

      // Step 1: Generate
      log('generate', 'running');
      let website: any;
      try {
        website = await generateWebsite(command.trim());
        log('generate', 'completed', { title: website.title, html_length: website.html.length });
      } catch (e: any) {
        log('generate', 'failed', e.message);
        return Response.json({ error: 'Website generation failed', steps }, { status: 500 });
      }

      // Derive a slug from the generated title or the command
      const slug = slugify(website.title) || slugify(command.trim().split(' ').slice(0, 3).join('-')) || `site-${Date.now()}`;

      // Step 2: GitHub
      log('github', 'running');
      let github: any;
      try {
        github = await provisionGitHub(base44, slug, website);
        log('github', 'completed', github);
      } catch (e: any) {
        log('github', 'failed', e.message);
        return Response.json({ error: 'GitHub provisioning failed', steps, website }, { status: 500 });
      }

      // Step 3: Vercel
      log('vercel', 'running');
      let vercel: any;
      try {
        vercel = await provisionVercel(slug, github.repo);
        log('vercel', 'completed', vercel);
      } catch (e: any) {
        log('vercel', 'failed', e.message);
        // Non-fatal — GitHub repo is still there
      }

      // Step 4: Railway
      log('railway', 'running');
      let railway: any;
      try {
        railway = await provisionRailway(website.title);
        log('railway', 'completed', railway);
      } catch (e: any) {
        log('railway', 'failed', e.message);
      }

      // Step 5: Supabase
      log('supabase', 'running');
      let supabase: any;
      try {
        supabase = await provisionSupabase(slug);
        log('supabase', 'completed', supabase);
      } catch (e: any) {
        log('supabase', 'failed', e.message);
      }

      return Response.json({
        ok: true,
        command: command.trim(),
        website: { title: website.title, description: website.description, html_length: website.html.length },
        github,
        vercel,
        railway,
        supabase,
        steps,
        preview_html: website.html.slice(0, 200000),
      });
    }

    return Response.json({ error: `Unknown action: ${action}` }, { status: 400 });
  } catch (error: any) {
    return Response.json({ error: error.message, stack: error.stack }, { status: 500 });
  }
}